// CardVault TCG Master Collection (36 Carte con Blueprint Certificati CardTrader & YGOPRODeck)
const DEFAULT_CARDS = [
  {
    "id": 1,
    "num": 1,
    "name": "Aluber il Giullare di Despia",
    "englishName": "Aluber the Jester of Despia",
    "expansion": "Quarter Century Stampede",
    "code": "RA04-IT038",
    "rarity": "Quarter Century Secret Rare",
    "edition": "1st Edition",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/62962630.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/62962630.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/62962630.jpg",
    "cardType": "Effect Monster",
    "desc": "If this card is Normal or Special Summoned: You can add 1 \"Branded\" Spell/Trap from your Deck to your hand. If a face-up Fusion Monster you control is destroyed by battle, or leaves the field because of an opponent's card effect, while this card is in your GY: You can target 1 Effect Monster your opponent controls; Special Summon this card, and if you do, negate the targeted monster's effects until the end of this turn. You can only use 1 \"Aluber the Jester of Despia\" effect per turn, and only once that turn.",
    "archetype": "Despia",
    "atk": 1800,
    "def": 0,
    "level": 4,
    "attribute": "DARK",
    "ygoprodeckUrl": "https://ygoprodeck.com/card/aluber-the-jester-of-despia-12157",
    "ebMin": 4.08,
    "ebTrend": 4.9,
    "cmMin": 46.79,
    "cmTrend": 47.1,
    "updatedAt": "2026-08-18T15:41:18.155Z",
    "baseCmMin": 46.79,
    "baseCmTrend": 47.1
  },
  {
    "id": 2,
    "num": 2,
    "name": "Odino, Padre degli Aesir",
    "englishName": "Odin, Father of the Aesir",
    "expansion": "Storm of Ragnarok",
    "code": "STOR-IT040",
    "rarity": "Ghost Rare",
    "edition": "1st Edition",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 87,
    "cmTrend": 88.82,
    "ctMin": 90.63,
    "ctTrend": 90.63,
    "ebMin": 88.82,
    "ebTrend": 92.44,
    "baseCmMin": 87,
    "baseCmTrend": 88.82,
    "baseCtMin": 90.63,
    "baseCtTrend": 90.63,
    "baseEbMin": 88.82,
    "baseEbTrend": 92.44,
    "trendStatus": "stable",
    "trendPct": 0,
    "blueprintId": 80186,
    "cardTraderUrl": "https://www.cardtrader.com/it/cards/80186-odin-father-of-the-aesir-ghost-rare-storm-of-ragnarok",
    "ygoprodeckUrl": "https://ygoprodeck.com/card/odin-father-of-the-aesir-7782",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/93483212.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/93483212.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/93483212.jpg",
    "cardType": "Synchro Monster",
    "archetype": "Aesir",
    "desc": "1 \"Nordic Ascendant\" Tuner + 2+ non-Tuner monsters\r\nOnce per turn: You can make this card be unaffected by Spell/Trap effects until the end of this turn. Once per turn, during the End Phase, if this face-up card you controlled was destroyed by your opponent's card and sent to your GY this turn: You can banish 1 \"Nordic Ascendant\" Tuner from your GY; Special Summon this card. When Summoned this way: You can draw 1 card.",
    "activeListings": 39,
    "notes": "Blueprint CT: #80186 • [IT • Near Mint • 1ª Ed.] 3/39 copie",
    "matchedListings": 3,
    "filterLevel": "IT • Near Mint • 1ª Ed.",
    "updatedAt": "2026-08-18T14:42:53.610Z"
  },
  {
    "id": 3,
    "num": 3,
    "name": "Loki, Signore degli Aesir",
    "englishName": "Loki, Lord of the Aesir",
    "expansion": "Legendary Collection 5D's: Mega Pack",
    "code": "LC5D-IT190",
    "rarity": "Secret Rare",
    "edition": "1st Edition",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 4.2,
    "cmTrend": 4.53,
    "ctMin": 4.38,
    "ctTrend": 4.62,
    "ebMin": 4.29,
    "ebTrend": 4.71,
    "baseCmMin": 4.2,
    "baseCmTrend": 4.53,
    "baseCtMin": 4.38,
    "baseCtTrend": 4.62,
    "baseEbMin": 4.29,
    "baseEbTrend": 4.71,
    "trendStatus": "up",
    "trendPct": 5.5,
    "blueprintId": 69640,
    "cardTraderUrl": "https://www.cardtrader.com/it/cards/69640-loki-lord-of-the-aesir-secret-rare-legendary-collection-5d-s-mega-pack",
    "ygoprodeckUrl": "https://ygoprodeck.com/card/loki-lord-of-the-aesir-5637",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/67098114.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/67098114.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/67098114.jpg",
    "cardType": "Synchro Monster",
    "archetype": "Aesir",
    "desc": "1 \"Nordic Alfar\" Tuner + 2+ non-Tuner monsters\r\nOnce per turn, when your opponent activates a Spell/Trap Card during your Battle Phase (Quick Effect): You can negate the activation, and if you do, destroy it. Once per turn, during the End Phase, if this face-up card you controlled was destroyed by your opponent's card and sent to your GY this turn: You can banish 1 \"Nordic Alfar\" Tuner from your GY; Special Summon this card. When Summoned this way: You can target 1 Trap in your GY; add that target to your hand.",
    "activeListings": 13,
    "notes": "Blueprint CT: #69640 • [IT • Near Mint • 1ª Ed.] 3/13 copie",
    "matchedListings": 3,
    "filterLevel": "IT • Near Mint • 1ª Ed.",
    "updatedAt": "2026-08-18T14:42:53.610Z"
  },
  {
    "id": 4,
    "num": 4,
    "name": "Loki, Signore degli Aesir",
    "englishName": "Loki, Lord of the Aesir",
    "expansion": "Storm of Ragnarok",
    "code": "STOR-IT039",
    "rarity": "Ultimate Rare",
    "edition": "1st Edition",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 14.39,
    "cmTrend": 25.33,
    "ctMin": 14.99,
    "ctTrend": 25.85,
    "ebMin": 14.69,
    "ebTrend": 26.37,
    "baseCmMin": 14.39,
    "baseCmTrend": 25.33,
    "baseCtMin": 14.99,
    "baseCtTrend": 25.85,
    "baseEbMin": 14.69,
    "baseEbTrend": 26.37,
    "trendStatus": "up",
    "trendPct": 72.4,
    "blueprintId": 80184,
    "cardTraderUrl": "https://www.cardtrader.com/it/cards/80184-loki-lord-of-the-aesir-ultimate-rare-storm-of-ragnarok",
    "ygoprodeckUrl": "https://ygoprodeck.com/card/loki-lord-of-the-aesir-5637",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/67098114.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/67098114.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/67098114.jpg",
    "cardType": "Synchro Monster",
    "archetype": "Aesir",
    "desc": "1 \"Nordic Alfar\" Tuner + 2+ non-Tuner monsters\r\nOnce per turn, when your opponent activates a Spell/Trap Card during your Battle Phase (Quick Effect): You can negate the activation, and if you do, destroy it. Once per turn, during the End Phase, if this face-up card you controlled was destroyed by your opponent's card and sent to your GY this turn: You can banish 1 \"Nordic Alfar\" Tuner from your GY; Special Summon this card. When Summoned this way: You can target 1 Trap in your GY; add that target to your hand.",
    "activeListings": 40,
    "notes": "Blueprint CT: #80184 • [IT • Near Mint • 1ª Ed.] 5/40 copie",
    "matchedListings": 5,
    "filterLevel": "IT • Near Mint • 1ª Ed.",
    "updatedAt": "2026-08-18T14:42:53.610Z"
  },
  {
    "id": 5,
    "num": 5,
    "name": "Thor, Signore degli Aesir",
    "englishName": "Thor, Lord of the Aesir",
    "expansion": "Storm of Ragnarok",
    "code": "STOR-IT038",
    "rarity": "Ultimate Rare",
    "edition": "1st Edition",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 26.3,
    "cmTrend": 30.84,
    "ctMin": 27.4,
    "ctTrend": 31.47,
    "ebMin": 26.85,
    "ebTrend": 32.1,
    "baseCmMin": 26.3,
    "baseCmTrend": 30.84,
    "baseCtMin": 27.4,
    "baseCtTrend": 31.47,
    "baseEbMin": 26.85,
    "baseEbTrend": 32.1,
    "trendStatus": "up",
    "trendPct": 14.9,
    "blueprintId": 80182,
    "cardTraderUrl": "https://www.cardtrader.com/it/cards/80182-thor-lord-of-the-aesir-ultimate-rare-storm-of-ragnarok",
    "ygoprodeckUrl": "https://ygoprodeck.com/card/thor-lord-of-the-aesir-2601",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/30604579.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/30604579.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/30604579.jpg",
    "cardType": "Synchro Monster",
    "archetype": "Aesir",
    "desc": "1 \"Nordic Beast\" Tuner + 2+ non-Tuner monsters\r\nOnce per turn: You can negate the effects of all face-up monsters your opponent currently controls, until the end of this turn. Once per turn, during the End Phase, if this face-up card you controlled was destroyed by your opponent's card and sent to your GY this turn: You can banish 1 \"Nordic Beast\" Tuner from your GY; Special Summon this card. If Summoned this way: Inflict 800 damage to your opponent.",
    "activeListings": 38,
    "notes": "Blueprint CT: #80182 • [IT • Near Mint • 1ª Ed.] 4/38 copie",
    "matchedListings": 4,
    "filterLevel": "IT • Near Mint • 1ª Ed.",
    "updatedAt": "2026-08-18T14:42:53.610Z"
  },
  {
    "id": 6,
    "num": 6,
    "name": "Drago Flusso di Vita",
    "englishName": "Life Stream Dragon",
    "expansion": "Legendary Collection 5D's: Mega Pack",
    "code": "LC5D-IT246",
    "rarity": "Common",
    "edition": "1st Edition",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 28.7,
    "cmTrend": 46.32,
    "ctMin": 29.9,
    "ctTrend": 47.27,
    "ebMin": 29.3,
    "ebTrend": 48.22,
    "baseCmMin": 28.7,
    "baseCmTrend": 46.32,
    "baseCtMin": 29.9,
    "baseCtTrend": 47.27,
    "baseEbMin": 29.3,
    "baseEbTrend": 48.22,
    "trendStatus": "up",
    "trendPct": 58.1,
    "blueprintId": 69697,
    "cardTraderUrl": "https://www.cardtrader.com/it/cards/69697-life-stream-dragon-common-legendary-collection-5d-s-mega-pack",
    "ygoprodeckUrl": "https://ygoprodeck.com/card/life-stream-dragon-2163",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/25165047.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/25165047.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/25165047.jpg",
    "cardType": "Synchro Tuner Monster",
    "archetype": "Power Tool",
    "desc": "1 Tuner + \"Power Tool Dragon\"\nWhen this card is Synchro Summoned: You can make your LP become 4000. You take no effect damage. If this face-up card on the field would be destroyed, you can banish 1 Equip Spell Card from your Graveyard instead.",
    "activeListings": 4,
    "notes": "Blueprint CT: #69697 • [IT • Near Mint • 1ª Ed.] 3/4 copie",
    "matchedListings": 3,
    "filterLevel": "IT • Near Mint • 1ª Ed.",
    "updatedAt": "2026-08-18T14:42:53.610Z"
  },
  {
    "id": 7,
    "num": 7,
    "name": "Arcidemone Sovrano dei Pensieri",
    "englishName": "Thought Ruler Archfiend",
    "expansion": "Legendary Collection 5D's: Mega Pack",
    "code": "LC5D-IT233",
    "rarity": "Secret Rare",
    "edition": "1st Edition",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 26.28,
    "cmTrend": 35.78,
    "ctMin": 27.38,
    "ctTrend": 36.51,
    "ebMin": 26.83,
    "ebTrend": 37.24,
    "baseCmMin": 26.28,
    "baseCmTrend": 35.78,
    "baseCtMin": 27.38,
    "baseCtTrend": 36.51,
    "baseEbMin": 26.83,
    "baseEbTrend": 37.24,
    "trendStatus": "up",
    "trendPct": 33.3,
    "blueprintId": 69683,
    "cardTraderUrl": "https://www.cardtrader.com/it/cards/69683-thought-ruler-archfiend-secret-rare-legendary-collection-5d-s-mega-pack",
    "ygoprodeckUrl": "https://ygoprodeck.com/card/thought-ruler-archfiend-5940",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/70780151.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/70780151.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/70780151.jpg",
    "cardType": "Synchro Monster",
    "archetype": "Archfiend",
    "desc": "1 Tuner + 1 or more non-Tuner monsters\nIf this card destroys a monster by battle and sends it to the Graveyard: Gain LP equal to that monster's original ATK in the Graveyard. During either player's turn, when a Spell/Trap Card is activated that targets exactly 1 Psychic-Type monster (and no other cards): You can pay 1000 LP; negate the activation, and if you do, destroy it.",
    "activeListings": 5,
    "notes": "Blueprint CT: #69683 • [IT • Near Mint • 1ª Ed.] 2/5 copie",
    "matchedListings": 2,
    "filterLevel": "IT • Near Mint • 1ª Ed.",
    "updatedAt": "2026-08-18T14:42:53.610Z"
  },
  {
    "id": 8,
    "num": 8,
    "name": "Maestro Armatura Ala Nera",
    "englishName": "Blackwing Armor Master",
    "expansion": "Legendary Collection 5D's: Mega Pack",
    "code": "LC5D-IT132",
    "rarity": "Secret Rare",
    "edition": "1st Edition",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 14.59,
    "cmTrend": 20.87,
    "ctMin": 15.2,
    "ctTrend": 21.3,
    "ebMin": 14.9,
    "ebTrend": 21.73,
    "baseCmMin": 14.59,
    "baseCmTrend": 20.87,
    "baseCtMin": 15.2,
    "baseCtTrend": 21.3,
    "baseEbMin": 14.9,
    "baseEbTrend": 21.73,
    "trendStatus": "up",
    "trendPct": 40.1,
    "blueprintId": 69581,
    "cardTraderUrl": "https://www.cardtrader.com/it/cards/69581-blackwing-armor-master-secret-rare-legendary-collection-5d-s-mega-pack",
    "ygoprodeckUrl": "https://ygoprodeck.com/card/blackwing-armor-master-5800",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/69031175.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/69031175.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/69031175.jpg",
    "cardType": "Synchro Monster",
    "archetype": "Blackwing",
    "desc": "1 \"Blackwing\" Tuner + 1 or more non-Tuner monsters\nCannot be destroyed by battle, and you take no battle damage from attacks involving this card. At the end of the Damage Step, if this card attacked a monster: You can place 1 Wedge Counter on that monster (max. 1). You can remove all Wedge Counters from your opponent's monsters; the ATK and DEF of those monsters that had Wedge Counters become 0 until the end of this turn.",
    "activeListings": 9,
    "notes": "Blueprint CT: #69581 • [IT (Tutte Cond.)] 2/9 copie",
    "matchedListings": 2,
    "filterLevel": "IT (Tutte Cond.)",
    "updatedAt": "2026-08-18T14:42:53.610Z"
  },
  {
    "id": 9,
    "num": 9,
    "name": "Drago Stella Maestoso",
    "englishName": "Majestic Star Dragon",
    "expansion": "Legendary Collection 5D's: Mega Pack",
    "code": "LC5D-IT036",
    "rarity": "Super Rare",
    "edition": "1st Edition",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 3.85,
    "cmTrend": 6.27,
    "ctMin": 4.01,
    "ctTrend": 6.4,
    "ebMin": 3.93,
    "ebTrend": 6.53,
    "baseCmMin": 3.85,
    "baseCmTrend": 6.27,
    "baseCtMin": 4.01,
    "baseCtTrend": 6.4,
    "baseEbMin": 3.93,
    "baseEbTrend": 6.53,
    "trendStatus": "up",
    "trendPct": 59.6,
    "blueprintId": 69484,
    "cardTraderUrl": "https://www.cardtrader.com/it/cards/69484-majestic-star-dragon-super-rare-legendary-collection-5d-s-mega-pack",
    "ygoprodeckUrl": "https://ygoprodeck.com/card/majestic-star-dragon-668",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/7841112.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/7841112.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/7841112.jpg",
    "cardType": "Synchro Monster",
    "archetype": "Majestic",
    "desc": "\"Majestic Dragon\" + \"Stardust Dragon\" + 1 non-Tuner monster\nDuring either player's turn, when your opponent activates a card or effect: You can Tribute this card; negate the activation, and if you do, destroy all cards your opponent controls. Once per turn: You can target 1 face-up monster your opponent controls; negate its effects until the end of this turn, and you can activate 1 of its effects as this card's effect once this turn. During the End Phase: Target 1 \"Stardust Dragon\" in your Graveyard; return this card from the field to the Extra Deck, then Special Summon that target.",
    "activeListings": 6,
    "notes": "Blueprint CT: #69484 • [IT (Tutte Cond.)] 3/6 copie",
    "matchedListings": 3,
    "filterLevel": "IT (Tutte Cond.)",
    "updatedAt": "2026-08-18T14:42:53.610Z"
  },
  {
    "id": 10,
    "num": 10,
    "name": "Antico Drago Fatato",
    "englishName": "Ancient Fairy Dragon",
    "expansion": "Legendary Collection 5D's: Mega Pack",
    "code": "LC5D-IT238",
    "rarity": "Ultra Rare",
    "edition": "1st Edition",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 6.73,
    "cmTrend": 7.43,
    "ctMin": 7.01,
    "ctTrend": 7.58,
    "ebMin": 6.87,
    "ebTrend": 7.73,
    "baseCmMin": 6.73,
    "baseCmTrend": 7.43,
    "baseCtMin": 7.01,
    "baseCtTrend": 7.58,
    "baseEbMin": 6.87,
    "baseEbTrend": 7.73,
    "trendStatus": "up",
    "trendPct": 8.1,
    "blueprintId": 69689,
    "cardTraderUrl": "https://www.cardtrader.com/it/cards/69689-ancient-fairy-dragon-ultra-rare-legendary-collection-5d-s-mega-pack",
    "ygoprodeckUrl": "https://ygoprodeck.com/card/ancient-fairy-dragon-2229",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/25862681.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/25862681.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/25862681.jpg",
    "cardType": "Synchro Monster",
    "archetype": "",
    "desc": "1 Tuner + 1+ non-Tuner monsters\r\nDuring your Main Phase: You can Special Summon 1 Level 4 or lower monster from your hand. You cannot conduct your Battle Phase the turn you activate this effect. During your Main Phase: You can destroy as many cards in the Field Zones as possible (min. 1), and if you do, gain 1000 LP, then you can add 1 Field Spell with a different name than the destroyed card(s), from your Deck to your hand. You can only use each effect of \"Ancient Fairy Dragon\" once per turn.",
    "activeListings": 15,
    "notes": "Blueprint CT: #69689 • [IT • Near Mint • 1ª Ed.] 2/15 copie",
    "matchedListings": 2,
    "filterLevel": "IT • Near Mint • 1ª Ed.",
    "updatedAt": "2026-08-18T14:42:53.610Z"
  },
  {
    "id": 11,
    "num": 11,
    "name": "Drago Quasar Sparante",
    "englishName": "Shooting Quasar Dragon",
    "expansion": "Legendary Collection 5D's",
    "code": "LC05-IT005",
    "rarity": "Ultra Rare",
    "edition": "1st Edition",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 7.46,
    "cmTrend": 14.04,
    "ctMin": 7.77,
    "ctTrend": 14.33,
    "ebMin": 7.61,
    "ebTrend": 14.62,
    "baseCmMin": 7.46,
    "baseCmTrend": 14.04,
    "baseCtMin": 7.77,
    "baseCtTrend": 14.33,
    "baseEbMin": 7.61,
    "baseEbTrend": 14.62,
    "trendStatus": "up",
    "trendPct": 84.4,
    "blueprintId": 80354,
    "cardTraderUrl": "https://www.cardtrader.com/it/cards/80354-shooting-quasar-dragon-ultra-rare-legendary-collection-5d-s",
    "ygoprodeckUrl": "https://ygoprodeck.com/card/shooting-quasar-dragon-3040",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/35952884.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/35952884.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/35952884.jpg",
    "cardType": "Synchro Monster",
    "archetype": "",
    "desc": "1 Tuner Synchro Monster + 2 or more non-Tuner Synchro Monsters\nMust be Synchro Summoned, and cannot be Special Summoned by other ways. This card's maximum number of attacks per Battle Phase equals the number of non-Tuner monsters used as its Synchro Material. Once per turn, during either player's turn, when a card or effect is activated: You can negate the activation, and if you do, destroy it. When this card leaves the field: You can Special Summon 1 \"Shooting Star Dragon\" from your Extra Deck.",
    "activeListings": 21,
    "notes": "Blueprint CT: #80354 • [IT • Near Mint] 6/21 copie",
    "matchedListings": 6,
    "filterLevel": "IT • Near Mint",
    "updatedAt": "2026-08-18T14:42:53.610Z"
  },
  {
    "id": 12,
    "num": 12,
    "name": "Jormungardr il Serpente Nordic",
    "englishName": "Jormungardr the Nordic Serpent",
    "expansion": "Legendary Collection 5D's",
    "code": "LC05-IT001",
    "rarity": "Ultra Rare",
    "edition": "1st Edition",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 0.32,
    "cmTrend": 0.34,
    "ctMin": 0.33,
    "ctTrend": 0.35,
    "ebMin": 0.32,
    "ebTrend": 0.36,
    "baseCmMin": 0.32,
    "baseCmTrend": 0.34,
    "baseCtMin": 0.33,
    "baseCtTrend": 0.35,
    "baseEbMin": 0.32,
    "baseEbTrend": 0.36,
    "trendStatus": "up",
    "trendPct": 6.1,
    "blueprintId": 80350,
    "cardTraderUrl": "https://www.cardtrader.com/it/cards/80350-jormungardr-the-nordic-serpent-ultra-rare-legendary-collection-5d-s",
    "ygoprodeckUrl": "https://ygoprodeck.com/card/jormungardr-the-nordic-serpent-5416",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/64203620.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/64203620.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/64203620.jpg",
    "cardType": "Effect Monster",
    "archetype": "Aesir",
    "desc": "Cannot be Normal Summoned/Set. If an \"Aesir\" monster is on the field, you can Special Summon this card (from your hand) to your opponent's side of the field in Defense Position. If an \"Aesir\" monster is not on the field, destroy this card. If this face-up Defense Position card you control is changed to face-up Attack Position: Take 3000 damage. This effect can only be used once while this card is face-up on the field.",
    "activeListings": 60,
    "notes": "Blueprint CT: #80350 • [IT • Near Mint] 13/60 copie",
    "matchedListings": 13,
    "filterLevel": "IT • Near Mint",
    "updatedAt": "2026-08-18T14:42:53.610Z"
  },
  {
    "id": 13,
    "num": 13,
    "name": "Fenrir il Lupo Nordic",
    "englishName": "Fenrir the Nordic Wolf",
    "expansion": "Legendary Collection 5D's",
    "code": "LC05-IT002",
    "rarity": "Ultra Rare",
    "edition": "1st Edition",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 0.18,
    "cmTrend": 0.34,
    "ctMin": 0.19,
    "ctTrend": 0.35,
    "ebMin": 0.19,
    "ebTrend": 0.36,
    "baseCmMin": 0.18,
    "baseCmTrend": 0.34,
    "baseCtMin": 0.19,
    "baseCtTrend": 0.35,
    "baseEbMin": 0.19,
    "baseEbTrend": 0.36,
    "trendStatus": "up",
    "trendPct": 84.2,
    "blueprintId": 80351,
    "cardTraderUrl": "https://www.cardtrader.com/it/cards/80351-fenrir-the-nordic-wolf-ultra-rare-legendary-collection-5d-s",
    "ygoprodeckUrl": "https://ygoprodeck.com/card/fenrir-the-nordic-wolf-7647",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/91697229.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/91697229.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/91697229.jpg",
    "cardType": "Effect Monster",
    "archetype": "Aesir",
    "desc": "Cannot be Normal Summoned/Set. During your Main Phase 2, if an \"Aesir\" monster is on the field, you can Special Summon this card (from your hand) to your opponent's side of the field in Defense Position. If an \"Aesir\" monster is not on the field, destroy this card. At the start of your Battle Phase: Change all Defense Position monsters you control to face-up Attack Position. Both players take any battle damage involving this card.",
    "activeListings": 47,
    "notes": "Blueprint CT: #80351 • [IT • Near Mint] 9/47 copie",
    "matchedListings": 9,
    "filterLevel": "IT • Near Mint",
    "updatedAt": "2026-08-18T14:42:53.610Z"
  },
  {
    "id": 14,
    "num": 14,
    "name": "Codificatore Trasmittente",
    "englishName": "Accesscode Talker",
    "expansion": "Maximum Gold: El Dorado",
    "code": "MGED-IT037",
    "rarity": "Premium Gold Rare",
    "edition": "1st Edition",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 2.14,
    "cmTrend": 3.72,
    "ctMin": 2.23,
    "ctTrend": 3.8,
    "ebMin": 2.19,
    "ebTrend": 3.88,
    "baseCmMin": 2.14,
    "baseCmTrend": 3.72,
    "baseCtMin": 2.23,
    "baseCtTrend": 3.8,
    "baseEbMin": 2.19,
    "baseEbTrend": 3.88,
    "trendStatus": "up",
    "trendPct": 70.4,
    "blueprintId": 197750,
    "cardTraderUrl": "https://www.cardtrader.com/it/cards/197750-accesscode-talker-premium-gold-rare-maximum-gold-el-dorado",
    "ygoprodeckUrl": "https://ygoprodeck.com/card/accesscode-talker-10731",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/86066372.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/86066372.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/86066372.jpg",
    "cardType": "Link Monster",
    "archetype": "Code Talker",
    "desc": "2+ Effect Monsters\r\nYour opponent cannot activate cards or effects in response to this card's effect activations. If this card is Link Summoned: You can target 1 Link Monster that was used as material for its Link Summon; this card gains ATK equal to that monster's Link Rating x 1000. You can banish 1 Link Monster from your field or GY; destroy 1 card your opponent controls, also for the rest of this turn, you cannot banish monsters with that same Attribute to activate this effect of \"Accesscode Talker\".",
    "activeListings": 42,
    "notes": "Blueprint CT: #197750 • [IT • Near Mint • 1ª Ed.] 7/42 copie",
    "matchedListings": 7,
    "filterLevel": "IT • Near Mint • 1ª Ed.",
    "updatedAt": "2026-08-18T14:42:53.610Z"
  },
  {
    "id": 15,
    "num": 15,
    "name": "Obelisk il Tormentatore",
    "englishName": "Obelisk the Tormentor",
    "expansion": "Quarter Century Bonanza",
    "code": "RA03-IT230",
    "rarity": "Platinum Secret Rare",
    "edition": "1st Edition",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 6.54,
    "cmTrend": 8.2,
    "ctMin": 6.81,
    "ctTrend": 8.37,
    "ebMin": 6.67,
    "ebTrend": 8.54,
    "baseCmMin": 6.54,
    "baseCmTrend": 8.2,
    "baseCtMin": 6.81,
    "baseCtTrend": 8.37,
    "baseEbMin": 6.67,
    "baseEbTrend": 8.54,
    "trendStatus": "up",
    "trendPct": 22.9,
    "blueprintId": 309870,
    "cardTraderUrl": "https://www.cardtrader.com/it/cards/309870-obelisk-the-tormentor-platinum-secret-rare-quarter-century-bonanza",
    "ygoprodeckUrl": "https://ygoprodeck.com/card/obelisk-the-tormentor-847",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/10000000.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/10000000.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/10000000.jpg",
    "cardType": "Effect Monster",
    "archetype": "Egyptian God",
    "desc": "Requires 3 Tributes to Normal Summon (cannot be Normal Set). This card's Normal Summon cannot be negated. When Normal Summoned, cards and effects cannot be activated. Neither player can target this card with card effects. Once per turn, during the End Phase, if this card was Special Summoned: Send it to the GY. You can Tribute 2 monsters; destroy all monsters your opponent controls. This card cannot declare an attack the turn this effect is activated.",
    "activeListings": 21,
    "notes": "Blueprint CT: #309870 • [IT • Near Mint • 1ª Ed.] 4/21 copie",
    "matchedListings": 4,
    "filterLevel": "IT • Near Mint • 1ª Ed.",
    "updatedAt": "2026-08-18T14:42:53.610Z"
  },
  {
    "id": 16,
    "num": 16,
    "name": "Obelisk il Tormentatore",
    "englishName": "Obelisk the Tormentor",
    "expansion": "Quarter Century Stampede",
    "code": "RA04-IT116",
    "rarity": "Quarter Century Secret Rare",
    "edition": "1st Edition",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 16.53,
    "cmTrend": 22.04,
    "ctMin": 17.22,
    "ctTrend": 22.49,
    "ebMin": 16.88,
    "ebTrend": 22.94,
    "baseCmMin": 16.53,
    "baseCmTrend": 22.04,
    "baseCtMin": 17.22,
    "baseCtTrend": 22.49,
    "baseEbMin": 16.88,
    "baseEbTrend": 22.94,
    "trendStatus": "up",
    "trendPct": 30.6,
    "blueprintId": 328973,
    "cardTraderUrl": "https://www.cardtrader.com/it/cards/328973-obelisk-the-tormentor-quarter-century-secret-rare-quarter-century-stampede",
    "ygoprodeckUrl": "https://ygoprodeck.com/card/obelisk-the-tormentor-847",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/10000000.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/10000000.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/10000000.jpg",
    "cardType": "Effect Monster",
    "archetype": "Egyptian God",
    "desc": "Requires 3 Tributes to Normal Summon (cannot be Normal Set). This card's Normal Summon cannot be negated. When Normal Summoned, cards and effects cannot be activated. Neither player can target this card with card effects. Once per turn, during the End Phase, if this card was Special Summoned: Send it to the GY. You can Tribute 2 monsters; destroy all monsters your opponent controls. This card cannot declare an attack the turn this effect is activated.",
    "activeListings": 13,
    "notes": "Blueprint CT: #328973 • [IT • Near Mint • 1ª Ed.] 4/13 copie",
    "matchedListings": 4,
    "filterLevel": "IT • Near Mint • 1ª Ed.",
    "updatedAt": "2026-08-18T14:42:53.610Z"
  },
  {
    "id": 17,
    "num": 17,
    "name": "Obelisk il Tormentatore",
    "englishName": "Obelisk the Tormentor",
    "expansion": "2019 Gold Sarcophagus Tin",
    "code": "TN19-IT007",
    "rarity": "Secret Rare",
    "edition": "1st Edition",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 3.13,
    "cmTrend": 3.91,
    "ctMin": 3.26,
    "ctTrend": 3.99,
    "ebMin": 3.19,
    "ebTrend": 4.07,
    "baseCmMin": 3.13,
    "baseCmTrend": 3.91,
    "baseCtMin": 3.26,
    "baseCtTrend": 3.99,
    "baseEbMin": 3.19,
    "baseEbTrend": 4.07,
    "trendStatus": "up",
    "trendPct": 22.4,
    "blueprintId": 66551,
    "cardTraderUrl": "https://www.cardtrader.com/it/cards/66551-obelisk-the-tormentor-secret-rare-2019-gold-sarcophagus-tin",
    "ygoprodeckUrl": "https://ygoprodeck.com/card/obelisk-the-tormentor-847",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/10000000.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/10000000.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/10000000.jpg",
    "cardType": "Effect Monster",
    "archetype": "Egyptian God",
    "desc": "Requires 3 Tributes to Normal Summon (cannot be Normal Set). This card's Normal Summon cannot be negated. When Normal Summoned, cards and effects cannot be activated. Neither player can target this card with card effects. Once per turn, during the End Phase, if this card was Special Summoned: Send it to the GY. You can Tribute 2 monsters; destroy all monsters your opponent controls. This card cannot declare an attack the turn this effect is activated.",
    "activeListings": 42,
    "notes": "Blueprint CT: #66551 • [IT • Near Mint • 1ª Ed.] 3/42 copie",
    "matchedListings": 3,
    "filterLevel": "IT • Near Mint • 1ª Ed.",
    "updatedAt": "2026-08-18T14:42:53.610Z"
  },
  {
    "id": 18,
    "num": 18,
    "name": "Slifer il Drago del Cielo",
    "englishName": "Slifer the Sky Dragon",
    "expansion": "Quarter Century Stampede",
    "code": "RA04-IT117",
    "rarity": "Quarter Century Secret Rare",
    "edition": "1st Edition",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 22.18,
    "cmTrend": 23.82,
    "ctMin": 23.1,
    "ctTrend": 24.31,
    "ebMin": 22.64,
    "ebTrend": 24.8,
    "baseCmMin": 22.18,
    "baseCmTrend": 23.82,
    "baseCtMin": 23.1,
    "baseCtTrend": 24.31,
    "baseEbMin": 22.64,
    "baseEbTrend": 24.8,
    "trendStatus": "up",
    "trendPct": 5.2,
    "blueprintId": 328975,
    "cardTraderUrl": "https://www.cardtrader.com/it/cards/328975-slifer-the-sky-dragon-quarter-century-secret-rare-quarter-century-stampede",
    "ygoprodeckUrl": "https://ygoprodeck.com/card/slifer-the-sky-dragon-854",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/10000020.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/10000020.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/10000020.jpg",
    "cardType": "Effect Monster",
    "archetype": "Egyptian God",
    "desc": "Requires 3 Tributes to Normal Summon (cannot be Normal Set). This card's Normal Summon cannot be negated. When Normal Summoned, cards and effects cannot be activated. Once per turn, during the End Phase, if this card was Special Summoned: Send it to the GY. Gains 1000 ATK/DEF for each card in your hand. If a monster(s) is Normal or Special Summoned to your opponent's field in Attack Position: That monster(s) loses 2000 ATK, then if its ATK has been reduced to 0 as a result, destroy it.",
    "activeListings": 13,
    "notes": "Blueprint CT: #328975 • [Globale • Near Mint] 13/13 copie",
    "matchedListings": 13,
    "filterLevel": "Globale • Near Mint",
    "updatedAt": "2026-08-18T14:42:53.610Z"
  },
  {
    "id": 19,
    "num": 19,
    "name": "Slifer il Drago del Cielo",
    "englishName": "Slifer the Sky Dragon",
    "expansion": "Quarter Century Bonanza",
    "code": "RA03-IT244",
    "rarity": "Platinum Secret Rare",
    "edition": "1st Edition",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 4.41,
    "cmTrend": 7.22,
    "ctMin": 4.59,
    "ctTrend": 7.37,
    "ebMin": 4.5,
    "ebTrend": 7.52,
    "baseCmMin": 4.41,
    "baseCmTrend": 7.22,
    "baseCtMin": 4.59,
    "baseCtTrend": 7.37,
    "baseEbMin": 4.5,
    "baseEbTrend": 7.52,
    "trendStatus": "up",
    "trendPct": 60.6,
    "blueprintId": 309898,
    "cardTraderUrl": "https://www.cardtrader.com/it/cards/309898-slifer-the-sky-dragon-platinum-secret-rare-quarter-century-bonanza",
    "ygoprodeckUrl": "https://ygoprodeck.com/card/slifer-the-sky-dragon-854",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/10000020.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/10000020.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/10000020.jpg",
    "cardType": "Effect Monster",
    "archetype": "Egyptian God",
    "desc": "Requires 3 Tributes to Normal Summon (cannot be Normal Set). This card's Normal Summon cannot be negated. When Normal Summoned, cards and effects cannot be activated. Once per turn, during the End Phase, if this card was Special Summoned: Send it to the GY. Gains 1000 ATK/DEF for each card in your hand. If a monster(s) is Normal or Special Summoned to your opponent's field in Attack Position: That monster(s) loses 2000 ATK, then if its ATK has been reduced to 0 as a result, destroy it.",
    "activeListings": 20,
    "notes": "Blueprint CT: #309898 • [IT • Near Mint • 1ª Ed.] 7/20 copie",
    "matchedListings": 7,
    "filterLevel": "IT • Near Mint • 1ª Ed.",
    "updatedAt": "2026-08-18T14:42:53.610Z"
  },
  {
    "id": 20,
    "num": 20,
    "name": "Slifer il Drago del Cielo",
    "englishName": "Slifer the Sky Dragon",
    "expansion": "2019 Gold Sarcophagus Tin",
    "code": "TN19-IT008",
    "rarity": "Secret Rare",
    "edition": "1st Edition",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 7.33,
    "cmTrend": 7.49,
    "ctMin": 7.64,
    "ctTrend": 7.64,
    "ebMin": 7.49,
    "ebTrend": 7.79,
    "baseCmMin": 7.33,
    "baseCmTrend": 7.49,
    "baseCtMin": 7.64,
    "baseCtTrend": 7.64,
    "baseEbMin": 7.49,
    "baseEbTrend": 7.79,
    "trendStatus": "stable",
    "trendPct": 0,
    "blueprintId": 66552,
    "cardTraderUrl": "https://www.cardtrader.com/it/cards/66552-slifer-the-sky-dragon-secret-rare-2019-gold-sarcophagus-tin",
    "ygoprodeckUrl": "https://ygoprodeck.com/card/slifer-the-sky-dragon-854",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/10000020.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/10000020.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/10000020.jpg",
    "cardType": "Effect Monster",
    "archetype": "Egyptian God",
    "desc": "Requires 3 Tributes to Normal Summon (cannot be Normal Set). This card's Normal Summon cannot be negated. When Normal Summoned, cards and effects cannot be activated. Once per turn, during the End Phase, if this card was Special Summoned: Send it to the GY. Gains 1000 ATK/DEF for each card in your hand. If a monster(s) is Normal or Special Summoned to your opponent's field in Attack Position: That monster(s) loses 2000 ATK, then if its ATK has been reduced to 0 as a result, destroy it.",
    "activeListings": 25,
    "notes": "Blueprint CT: #66552 • [IT • Near Mint • 1ª Ed.] 1/25 copie",
    "matchedListings": 1,
    "filterLevel": "IT • Near Mint • 1ª Ed.",
    "updatedAt": "2026-08-18T14:42:53.610Z"
  },
  {
    "id": 21,
    "num": 21,
    "name": "Drago Alato di Ra",
    "englishName": "The Winged Dragon of Ra",
    "expansion": "2019 Gold Sarcophagus Tin",
    "code": "TN19-IT009",
    "rarity": "Secret Rare",
    "edition": "1st Edition",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 2.69,
    "cmTrend": 5.63,
    "ctMin": 2.8,
    "ctTrend": 5.75,
    "ebMin": 2.74,
    "ebTrend": 5.87,
    "baseCmMin": 2.69,
    "baseCmTrend": 5.63,
    "baseCtMin": 2.8,
    "baseCtTrend": 5.75,
    "baseEbMin": 2.74,
    "baseEbTrend": 5.87,
    "trendStatus": "up",
    "trendPct": 105.4,
    "blueprintId": 66553,
    "cardTraderUrl": "https://www.cardtrader.com/it/cards/66553-the-winged-dragon-of-ra-secret-rare-2019-gold-sarcophagus-tin",
    "ygoprodeckUrl": "https://ygoprodeck.com/card/the-winged-dragon-of-ra-850",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/10000010.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/10000010.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/10000010.jpg",
    "cardType": "Effect Monster",
    "archetype": "Egyptian God",
    "desc": "Cannot be Special Summoned. Requires 3 Tributes to Normal Summon (cannot be Normal Set). This card's Normal Summon cannot be negated. When Normal Summoned, other cards and effects cannot be activated. When this card is Normal Summoned: You can pay LP so that you only have 100 left; this card gains ATK/DEF equal to the amount of LP paid. You can pay 1000 LP, then target 1 monster on the field; destroy that target.",
    "activeListings": 29,
    "notes": "Blueprint CT: #66553 • [IT • Near Mint] 8/29 copie",
    "matchedListings": 8,
    "filterLevel": "IT • Near Mint",
    "updatedAt": "2026-08-18T14:42:53.610Z"
  },
  {
    "id": 22,
    "num": 22,
    "name": "Drago Alato di Ra",
    "englishName": "The Winged Dragon of Ra",
    "expansion": "Quarter Century Stampede",
    "code": "RA04-IT118",
    "rarity": "Quarter Century Secret Rare",
    "edition": "1st Edition",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 29.16,
    "cmTrend": 44.9,
    "ctMin": 30.38,
    "ctTrend": 45.82,
    "ebMin": 29.77,
    "ebTrend": 46.74,
    "baseCmMin": 29.16,
    "baseCmTrend": 44.9,
    "baseCtMin": 30.38,
    "baseCtTrend": 45.82,
    "baseEbMin": 29.77,
    "baseEbTrend": 46.74,
    "trendStatus": "up",
    "trendPct": 50.8,
    "blueprintId": 328977,
    "cardTraderUrl": "https://www.cardtrader.com/it/cards/328977-the-winged-dragon-of-ra-quarter-century-secret-rare-quarter-century-stampede",
    "ygoprodeckUrl": "https://ygoprodeck.com/card/the-winged-dragon-of-ra-850",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/10000010.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/10000010.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/10000010.jpg",
    "cardType": "Effect Monster",
    "archetype": "Egyptian God",
    "desc": "Cannot be Special Summoned. Requires 3 Tributes to Normal Summon (cannot be Normal Set). This card's Normal Summon cannot be negated. When Normal Summoned, other cards and effects cannot be activated. When this card is Normal Summoned: You can pay LP so that you only have 100 left; this card gains ATK/DEF equal to the amount of LP paid. You can pay 1000 LP, then target 1 monster on the field; destroy that target.",
    "activeListings": 11,
    "notes": "Blueprint CT: #328977 • [IT • Near Mint • 1ª Ed.] 4/11 copie",
    "matchedListings": 4,
    "filterLevel": "IT • Near Mint • 1ª Ed.",
    "updatedAt": "2026-08-18T14:42:53.610Z"
  },
  {
    "id": 23,
    "num": 23,
    "name": "Drago Alato di Ra",
    "englishName": "The Winged Dragon of Ra",
    "expansion": "Quarter Century Bonanza",
    "code": "RA03-IT137",
    "rarity": "Platinum Secret Rare",
    "edition": "1st Edition",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 21.5,
    "cmTrend": 33.13,
    "ctMin": 22.4,
    "ctTrend": 33.81,
    "ebMin": 21.95,
    "ebTrend": 34.49,
    "baseCmMin": 21.5,
    "baseCmTrend": 33.13,
    "baseCtMin": 22.4,
    "baseCtTrend": 33.81,
    "baseEbMin": 21.95,
    "baseEbTrend": 34.49,
    "trendStatus": "up",
    "trendPct": 50.9,
    "blueprintId": 309684,
    "cardTraderUrl": "https://www.cardtrader.com/it/cards/309684-the-winged-dragon-of-ra-platinum-secret-rare-quarter-century-bonanza",
    "ygoprodeckUrl": "https://ygoprodeck.com/card/the-winged-dragon-of-ra-850",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/10000010.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/10000010.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/10000010.jpg",
    "cardType": "Effect Monster",
    "archetype": "Egyptian God",
    "desc": "Cannot be Special Summoned. Requires 3 Tributes to Normal Summon (cannot be Normal Set). This card's Normal Summon cannot be negated. When Normal Summoned, other cards and effects cannot be activated. When this card is Normal Summoned: You can pay LP so that you only have 100 left; this card gains ATK/DEF equal to the amount of LP paid. You can pay 1000 LP, then target 1 monster on the field; destroy that target.",
    "activeListings": 7,
    "notes": "Blueprint CT: #309684 • [IT • Near Mint • 1ª Ed.] 4/7 copie",
    "matchedListings": 4,
    "filterLevel": "IT • Near Mint • 1ª Ed.",
    "updatedAt": "2026-08-18T14:42:53.610Z"
  },
  {
    "id": 24,
    "num": 24,
    "name": "Aleister l'Invocatore",
    "englishName": "Aleister the Invoker",
    "expansion": "Quarter Century Stampede",
    "code": "RA04-IT024",
    "rarity": "Quarter Century Secret Rare",
    "edition": "1st Edition",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 38.85,
    "cmTrend": 39.97,
    "ctMin": 40.47,
    "ctTrend": 40.79,
    "ebMin": 39.66,
    "ebTrend": 41.61,
    "baseCmMin": 38.85,
    "baseCmTrend": 39.97,
    "baseCtMin": 40.47,
    "baseCtTrend": 40.79,
    "baseEbMin": 39.66,
    "baseEbTrend": 41.61,
    "trendStatus": "up",
    "trendPct": 0.8,
    "blueprintId": 329299,
    "cardTraderUrl": "https://www.cardtrader.com/it/cards/329299-aleister-the-invoker-quarter-century-secret-rare-quarter-century-stampede",
    "ygoprodeckUrl": "https://ygoprodeck.com/card/aleister-the-invoker-7213",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/86120751.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/86120751.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/86120751.jpg",
    "cardType": "Effect Monster",
    "archetype": "Invoked",
    "desc": "(Quick Effect): You can send this card from your hand to the GY, then target 1 Fusion Monster you control; it gains 1000 ATK/DEF until the end of this turn. If this card is Normal Summoned or flipped face-up: You can add 1 \"Invocation\" from your Deck to your hand.",
    "activeListings": 7,
    "notes": "Blueprint CT: #329299 • [IT • Near Mint • 1ª Ed.] 2/7 copie",
    "matchedListings": 2,
    "filterLevel": "IT • Near Mint • 1ª Ed.",
    "updatedAt": "2026-08-18T14:42:53.610Z"
  },
  {
    "id": 25,
    "num": 25,
    "name": "Prigione Dimensionale",
    "englishName": "Dimensional Prison",
    "expansion": "Quarter Century Stampede",
    "code": "RA04-IT132",
    "rarity": "Platinum Secret Rare",
    "edition": "1st Edition",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 19.46,
    "cmTrend": 19.86,
    "ctMin": 20.27,
    "ctTrend": 20.27,
    "ebMin": 19.86,
    "ebTrend": 20.68,
    "baseCmMin": 19.46,
    "baseCmTrend": 19.86,
    "baseCtMin": 20.27,
    "baseCtTrend": 20.27,
    "baseEbMin": 19.86,
    "baseEbTrend": 20.68,
    "trendStatus": "stable",
    "trendPct": 0,
    "blueprintId": 329004,
    "cardTraderUrl": "https://www.cardtrader.com/it/cards/329004-dimensional-prison-platinum-secret-rare-quarter-century-stampede",
    "ygoprodeckUrl": "https://ygoprodeck.com/card/dimensional-prison-5917",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/70342110.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/70342110.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/70342110.jpg",
    "cardType": "Trap Card",
    "archetype": "",
    "desc": "When an opponent's monster declares an attack: Target that attacking monster; banish that target.",
    "activeListings": 10,
    "notes": "Blueprint CT: #329004 • [IT • Near Mint • 1ª Ed.] 1/10 copie",
    "matchedListings": 1,
    "filterLevel": "IT • Near Mint • 1ª Ed.",
    "updatedAt": "2026-08-18T14:42:53.610Z"
  },
  {
    "id": 26,
    "num": 26,
    "name": "Uria, Signore delle Fiamme Impetuose",
    "englishName": "Uria, Lord of Searing Flames",
    "expansion": "Shadow of Infinity",
    "code": "SOI-IT001",
    "rarity": "Ultimate Rare",
    "edition": "1st Edition",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 768.6,
    "cmTrend": 1274.62,
    "ctMin": 800.63,
    "ctTrend": 1300.63,
    "ebMin": 784.62,
    "ebTrend": 1326.64,
    "baseCmMin": 768.6,
    "baseCmTrend": 1274.62,
    "baseCtMin": 800.63,
    "baseCtTrend": 1300.63,
    "baseEbMin": 784.62,
    "baseEbTrend": 1326.64,
    "trendStatus": "up",
    "trendPct": 62.5,
    "blueprintId": 62979,
    "cardTraderUrl": "https://www.cardtrader.com/it/cards/62979-uria-lord-of-searing-flames-ultimate-rare-shadow-of-infinity",
    "ygoprodeckUrl": "https://ygoprodeck.com/card/uria-lord-of-searing-flames-527",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/6007213.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/6007213.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/6007213.jpg",
    "cardType": "Effect Monster",
    "archetype": "Sacred Beast",
    "desc": "Cannot be Normal Summoned/Set. Must be Special Summoned (from your hand) by sending 3 face-up Traps you control to the GY. Gains 1000 ATK for each Continuous Trap in your GY. Once per turn: You can target 1 Set Spell/Trap your opponent controls; destroy that target. Neither player can activate Spell/Trap Cards in response to this effect's activation.",
    "activeListings": 11,
    "notes": "Blueprint CT: #62979 • [IT • Near Mint • 1ª Ed.] 2/11 copie",
    "matchedListings": 2,
    "filterLevel": "IT • Near Mint • 1ª Ed.",
    "updatedAt": "2026-08-18T14:42:53.610Z"
  },
  {
    "id": 27,
    "num": 27,
    "name": "Hamon, Signore del Tuono Scioccante",
    "englishName": "Hamon, Lord of Striking Thunder",
    "expansion": "Shadow of Infinity",
    "code": "SOI-IT002",
    "rarity": "Ultimate Rare",
    "edition": "1st Edition",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 480.61,
    "cmTrend": 490.63,
    "ctMin": 500.64,
    "ctTrend": 500.64,
    "ebMin": 490.63,
    "ebTrend": 510.65,
    "baseCmMin": 480.61,
    "baseCmTrend": 490.63,
    "baseCtMin": 500.64,
    "baseCtTrend": 500.64,
    "baseEbMin": 490.63,
    "baseEbTrend": 510.65,
    "trendStatus": "stable",
    "trendPct": 0,
    "blueprintId": 62981,
    "cardTraderUrl": "https://www.cardtrader.com/it/cards/62981-hamon-lord-of-striking-thunder-ultimate-rare-shadow-of-infinity",
    "ygoprodeckUrl": "https://ygoprodeck.com/card/hamon-lord-of-striking-thunder-2764",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/32491822.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/32491822.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/32491822.jpg",
    "cardType": "Effect Monster",
    "archetype": "Sacred Beast",
    "desc": "Cannot be Normal Summoned/Set. Must be Special Summoned (from your hand) by sending 3 face-up Continuous Spell Cards you control to the Graveyard, and cannot be Special Summoned by other ways. If this card destroys an opponent's monster by battle and sends it to the Graveyard: Inflict 1000 damage to your opponent. While this card is in face-up Defense Position, monsters your opponent controls cannot target monsters for attacks, except this one.",
    "activeListings": 18,
    "notes": "Blueprint CT: #62981 • [IT • Near Mint • 1ª Ed.] 3/18 copie",
    "matchedListings": 3,
    "filterLevel": "IT • Near Mint • 1ª Ed.",
    "updatedAt": "2026-08-18T14:42:53.610Z"
  },
  {
    "id": 28,
    "num": 28,
    "name": "Raviel, il Signore dei Fantasmi",
    "englishName": "Raviel, Lord of Phantasms",
    "expansion": "Shadow of Infinity",
    "code": "SOI-IT003",
    "rarity": "Ultimate Rare",
    "edition": "1st Edition",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 96.61,
    "cmTrend": 207.73,
    "ctMin": 100.64,
    "ctTrend": 211.97,
    "ebMin": 98.63,
    "ebTrend": 216.21,
    "baseCmMin": 96.61,
    "baseCmTrend": 207.73,
    "baseCtMin": 100.64,
    "baseCtTrend": 211.97,
    "baseEbMin": 98.63,
    "baseEbTrend": 216.21,
    "trendStatus": "up",
    "trendPct": 110.6,
    "blueprintId": 62983,
    "cardTraderUrl": "https://www.cardtrader.com/it/cards/62983-raviel-lord-of-phantasms-ultimate-rare-shadow-of-infinity",
    "ygoprodeckUrl": "https://ygoprodeck.com/card/raviel-lord-of-phantasms-5877",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/69890967.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/69890967.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/69890967.jpg",
    "cardType": "Effect Monster",
    "archetype": "Sacred Beast",
    "desc": "Cannot be Normal Summoned/Set. Must be Special Summoned (from your hand) by Tributing 3 Fiend-Type monsters, and cannot be Special Summoned by other ways. If your opponent Normal Summons a monster(s): Special Summon 1 \"Phantasm Token\" (Fiend-Type/DARK/Level 1/ATK 1000/DEF 1000) for each monster Summoned, but it cannot declare an attack. Once per turn: You can Tribute 1 monster; this card gains ATK equal to the original ATK of the Tributed monster until the end of this turn.",
    "activeListings": 25,
    "notes": "Blueprint CT: #62983 • [IT • Near Mint • 1ª Ed.] 5/25 copie",
    "matchedListings": 5,
    "filterLevel": "IT • Near Mint • 1ª Ed.",
    "updatedAt": "2026-08-18T14:42:53.610Z"
  },
  {
    "id": 29,
    "num": 29,
    "name": "Drago Fotonico Occhi Galattici Neo",
    "englishName": "Neo Galaxy-Eyes Photon Dragon",
    "expansion": "Battles of Legend: Light's Revenge",
    "code": "BLLR-IT064",
    "rarity": "Ultra Rare",
    "edition": "1st Edition",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 24.38,
    "cmTrend": 24.89,
    "ctMin": 25.4,
    "ctTrend": 25.4,
    "ebMin": 24.89,
    "ebTrend": 25.91,
    "baseCmMin": 24.38,
    "baseCmTrend": 24.89,
    "baseCtMin": 25.4,
    "baseCtTrend": 25.4,
    "baseEbMin": 24.89,
    "baseEbTrend": 25.91,
    "trendStatus": "stable",
    "trendPct": 0,
    "blueprintId": 80623,
    "cardTraderUrl": "https://www.cardtrader.com/it/cards/80623-neo-galaxy-eyes-photon-dragon-ultra-rare-battles-of-legend-light-s-revenge",
    "ygoprodeckUrl": "https://ygoprodeck.com/card/neo-galaxy-eyes-photon-dragon-3332",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/39272762.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/39272762.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/39272762.jpg",
    "cardType": "XYZ Monster",
    "archetype": "Galaxy-Eyes",
    "desc": "3 Level 8 monsters\r\nIf this card is Xyz Summoned using \"Galaxy-Eyes Photon Dragon\" as any of its materials: All other face-up cards currently on the field have their effects negated. Once per turn: You can detach 1 material from this card; detach all materials from monsters your opponent controls, then this card gains 500 ATK for each, also it can attack up to that many times during each Battle Phase this turn.",
    "activeListings": 16,
    "notes": "Blueprint CT: #80623 • [IT • Near Mint • 1ª Ed.] 2/16 copie",
    "matchedListings": 2,
    "filterLevel": "IT • Near Mint • 1ª Ed.",
    "updatedAt": "2026-08-18T14:42:53.610Z"
  },
  {
    "id": 30,
    "num": 30,
    "name": "Numero C62: Neo Drago Fotonico Primordiale",
    "englishName": "Number C62: Neo Galaxy-Eyes Prime Photon Dragon",
    "expansion": "Photon Hypernova",
    "code": "PHHY-IT043",
    "rarity": "Ultra Rare",
    "edition": "1st Edition",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 48.61,
    "cmTrend": 49.63,
    "ctMin": 50.64,
    "ctTrend": 50.64,
    "ebMin": 49.63,
    "ebTrend": 51.65,
    "baseCmMin": 48.61,
    "baseCmTrend": 49.63,
    "baseCtMin": 50.64,
    "baseCtTrend": 50.64,
    "baseEbMin": 49.63,
    "baseEbTrend": 51.65,
    "trendStatus": "stable",
    "trendPct": 0,
    "blueprintId": 236687,
    "cardTraderUrl": "https://www.cardtrader.com/it/cards/236687-number-c62-neo-galaxy-eyes-prime-photon-dragon-ultra-rare-photon-hypernova",
    "ygoprodeckUrl": "https://ygoprodeck.com/card/number-c62-neo-galaxy-eyes-prime-photon-dragon-13455",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/48348921.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/48348921.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/48348921.jpg",
    "cardType": "XYZ Monster",
    "archetype": "-Eyes Dragon",
    "desc": "3 Level 8 LIGHT monsters\r\nYou can also Xyz Summon this card by using \"Number 62: Galaxy-Eyes Prime Photon Dragon\" you control. (Transfer its materials to this card.) At the start of your Battle Phase: You can detach 1 material from this card; this card can make up to 3 attacks on monsters during this Battle Phase. If this card has \"Galaxy-Eyes Photon Dragon\" as material, it gains these effects.\r\n● Unaffected by your opponent's monster effects.\r\n● Gains ATK equal to the combined Levels/Ranks of its attached materials x 100.",
    "activeListings": 11,
    "notes": "Blueprint CT: #236687 • [IT • Near Mint • 1ª Ed.] 1/11 copie",
    "matchedListings": 1,
    "filterLevel": "IT • Near Mint • 1ª Ed.",
    "updatedAt": "2026-08-18T14:42:53.610Z"
  },
  {
    "id": 31,
    "num": 31,
    "name": "Numero 62: Drago Fotonico Primordiale",
    "englishName": "Number 62: Galaxy-Eyes Prime Photon Dragon",
    "expansion": "Battles of Legend: Light's Revenge",
    "code": "BLLR-IT070",
    "rarity": "Ultra Rare",
    "edition": "1st Edition",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 38.9,
    "cmTrend": 39.71,
    "ctMin": 40.52,
    "ctTrend": 40.52,
    "ebMin": 39.71,
    "ebTrend": 41.33,
    "baseCmMin": 38.9,
    "baseCmTrend": 39.71,
    "baseCtMin": 40.52,
    "baseCtTrend": 40.52,
    "baseEbMin": 39.71,
    "baseEbTrend": 41.33,
    "trendStatus": "stable",
    "trendPct": 0,
    "blueprintId": 80629,
    "cardTraderUrl": "https://www.cardtrader.com/it/cards/80629-number-62-galaxy-eyes-prime-photon-dragon-ultra-rare-battles-of-legend-light-s-revenge",
    "ygoprodeckUrl": "https://ygoprodeck.com/card/number-62-galaxy-eyes-prime-photon-dragon-2699",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/31801517.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/31801517.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/31801517.jpg",
    "cardType": "XYZ Monster",
    "archetype": "Galaxy-Eyes",
    "desc": "2 Level 8 monsters\r\nIf this card battles, during damage calculation (Quick Effect): You can detach 1 material from this card once per battle; this card gains ATK equal to the combined Ranks of all Xyz Monsters currently on the field x 200, during that damage calculation only. If this card in its owner's control is destroyed by an opponent's card effect while it has \"Galaxy-Eyes Photon Dragon\" as Xyz Material: You can Special Summon this card during your 2nd Standby Phase after activation and double its ATK. Any battle damage this card inflicts to your opponent is halved unless it has \"Galaxy-Eyes Photon Dragon\" as Xyz Material.",
    "activeListings": 12,
    "notes": "Blueprint CT: #80629 • [IT • Near Mint • 1ª Ed.] 1/12 copie",
    "matchedListings": 1,
    "filterLevel": "IT • Near Mint • 1ª Ed.",
    "updatedAt": "2026-08-18T14:42:53.610Z"
  },
  {
    "id": 32,
    "num": 32,
    "name": "Infernoid Onuncu",
    "englishName": "Infernoid Onuncu",
    "expansion": "Secrets of Eternity",
    "code": "SECE-IT019",
    "rarity": "Ultimate Rare",
    "edition": "1st Edition",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 9.73,
    "cmTrend": 12.31,
    "ctMin": 10.14,
    "ctTrend": 12.56,
    "ebMin": 9.94,
    "ebTrend": 12.81,
    "baseCmMin": 9.73,
    "baseCmTrend": 12.31,
    "baseCtMin": 10.14,
    "baseCtTrend": 12.56,
    "baseEbMin": 9.94,
    "baseEbTrend": 12.81,
    "trendStatus": "up",
    "trendPct": 23.9,
    "blueprintId": 84619,
    "cardTraderUrl": "https://www.cardtrader.com/it/cards/84619-infernoid-onuncu-ultimate-rare-secrets-of-eternity",
    "ygoprodeckUrl": "https://ygoprodeck.com/card/infernoid-onuncu-1270",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/14799437.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/14799437.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/14799437.jpg",
    "cardType": "Effect Monster",
    "archetype": "Infernoid",
    "desc": "Cannot be Normal Summoned/Set. Must be Special Summoned (from your hand or Graveyard) by banishing 3 \"Infernoid\" monsters from your hand or Graveyard while the total Levels and Ranks of all Effect Monsters you control are 8 or lower, and cannot be Special Summoned by other ways. When this card is Special Summoned: You can destroy all other monsters on the field. Once per turn, during either player's turn, when a Spell/Trap Card or effect is activated: You can Tribute 1 monster; negate the activation, and if you do, banish that card.",
    "activeListings": 41,
    "notes": "Blueprint CT: #84619 • [IT • Near Mint • 1ª Ed.] 16/41 copie",
    "matchedListings": 16,
    "filterLevel": "IT • Near Mint • 1ª Ed.",
    "updatedAt": "2026-08-18T14:42:53.610Z"
  },
  {
    "id": 33,
    "num": 33,
    "name": "Numero 89: Diablosis l'Hacker di Menti",
    "englishName": "Number 89: Diablosis the Mind Hacker",
    "expansion": "Brothers of Legend",
    "code": "BROL-IT073",
    "rarity": "Secret Rare",
    "edition": "1st Edition",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 9.25,
    "cmTrend": 9.7,
    "ctMin": 9.64,
    "ctTrend": 9.9,
    "ebMin": 9.45,
    "ebTrend": 10.1,
    "baseCmMin": 9.25,
    "baseCmTrend": 9.7,
    "baseCtMin": 9.64,
    "baseCtTrend": 9.9,
    "baseEbMin": 9.45,
    "baseEbTrend": 10.1,
    "trendStatus": "up",
    "trendPct": 2.7,
    "blueprintId": 201130,
    "cardTraderUrl": "https://www.cardtrader.com/it/cards/201130-number-89-diablosis-the-mind-hacker-secret-rare-brothers-of-legend",
    "ygoprodeckUrl": "https://ygoprodeck.com/card/number-89-diablosis-the-mind-hacker-8897",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/95474755.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/95474755.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/95474755.jpg",
    "cardType": "XYZ Monster",
    "archetype": "",
    "desc": "2 Level 7 monsters\r\nOnce per turn: You can detach 1 material from this card; look at your opponent's Extra Deck and banish 1 monster from it, face-down. At the end of the Battle Phase, if this card destroyed a monster by battle: You can target 1 card in your opponent's GY; banish it, face-down. If a card your opponent owns and possesses is banished face-down while you control this card (except during the Damage Step): You can banish cards from the top of your opponent's Deck, face-down, equal to their face-down banished cards. You can only use this effect of \"Number 89: Diablosis the Mind Hacker\" once per turn.",
    "activeListings": 32,
    "notes": "Blueprint CT: #201130 • [IT • Near Mint • 1ª Ed.] 8/32 copie",
    "matchedListings": 8,
    "filterLevel": "IT • Near Mint • 1ª Ed.",
    "updatedAt": "2026-08-18T14:42:53.610Z"
  },
  {
    "id": 34,
    "num": 34,
    "name": "Antico Drago Fatato",
    "englishName": "Ancient Fairy Dragon",
    "expansion": "25th Anniversary Rarity Collection",
    "code": "RA01-IT030",
    "rarity": "Quarter Century Secret Rare",
    "edition": "1st Edition",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 52.05,
    "cmTrend": 53.14,
    "ctMin": 54.22,
    "ctTrend": 54.22,
    "ebMin": 53.14,
    "ebTrend": 55.3,
    "baseCmMin": 52.05,
    "baseCmTrend": 53.14,
    "baseCtMin": 54.22,
    "baseCtTrend": 54.22,
    "baseEbMin": 53.14,
    "baseEbTrend": 55.3,
    "trendStatus": "stable",
    "trendPct": 0,
    "blueprintId": 265696,
    "cardTraderUrl": "https://www.cardtrader.com/it/cards/265696-ancient-fairy-dragon-quarter-century-secret-rare-25th-anniversary-rarity-collection",
    "ygoprodeckUrl": "https://ygoprodeck.com/card/ancient-fairy-dragon-2229",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/25862681.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/25862681.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/25862681.jpg",
    "cardType": "Synchro Monster",
    "archetype": "",
    "desc": "1 Tuner + 1+ non-Tuner monsters\r\nDuring your Main Phase: You can Special Summon 1 Level 4 or lower monster from your hand. You cannot conduct your Battle Phase the turn you activate this effect. During your Main Phase: You can destroy as many cards in the Field Zones as possible (min. 1), and if you do, gain 1000 LP, then you can add 1 Field Spell with a different name than the destroyed card(s), from your Deck to your hand. You can only use each effect of \"Ancient Fairy Dragon\" once per turn.",
    "activeListings": 16,
    "notes": "Blueprint CT: #265696 • [IT • Near Mint • 1ª Ed.] 1/16 copie",
    "matchedListings": 1,
    "filterLevel": "IT • Near Mint • 1ª Ed.",
    "updatedAt": "2026-08-18T14:42:53.610Z"
  },
  {
    "id": 35,
    "num": 35,
    "name": "Arcidemone Drago Rosso Assalto",
    "englishName": "Red Dragon Archfiend/Assault Mode",
    "expansion": "Crimson Crisis",
    "code": "CRMS-IT004",
    "rarity": "Ultimate Rare",
    "edition": "1st Edition",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 192.55,
    "cmTrend": 197.87,
    "ctMin": 200.57,
    "ctTrend": 201.91,
    "ebMin": 196.56,
    "ebTrend": 205.95,
    "baseCmMin": 192.55,
    "baseCmTrend": 197.87,
    "baseCtMin": 200.57,
    "baseCtTrend": 201.91,
    "baseEbMin": 196.56,
    "baseEbTrend": 205.95,
    "trendStatus": "up",
    "trendPct": 0.7,
    "blueprintId": 73262,
    "cardTraderUrl": "https://www.cardtrader.com/it/cards/73262-red-dragon-archfiend-assault-mode-ultimate-rare-crimson-crisis",
    "ygoprodeckUrl": "https://ygoprodeck.com/card/red-dragon-archfiend-assault-mode-6503",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/77336644.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/77336644.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/77336644.jpg",
    "cardType": "Effect Monster",
    "archetype": "Assault Mode",
    "desc": "This card cannot be Normal Summoned or Set. This card cannot be Special Summoned except with \"Assault Mode Activate\". If this card attacks, destroy all other monsters after damage calculation. When this card on the field is destroyed, you can Special Summon 1 \"Red Dragon Archfiend\" from your Graveyard.",
    "activeListings": 40,
    "notes": "Blueprint CT: #73262 • [IT • Near Mint • 1ª Ed.] 3/40 copie",
    "matchedListings": 3,
    "filterLevel": "IT • Near Mint • 1ª Ed.",
    "updatedAt": "2026-08-18T14:42:53.610Z"
  },
  {
    "id": 36,
    "num": 36,
    "name": "Drago Stellare Maestoso Cadente",
    "englishName": "Shooting Majestic Star Dragon",
    "expansion": "Dawn of Majesty",
    "code": "DAMA-IT039",
    "rarity": "Secret Rare",
    "edition": "1st Edition",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 47.99,
    "cmTrend": 68.02,
    "ctMin": 49.99,
    "ctTrend": 69.41,
    "ebMin": 48.99,
    "ebTrend": 70.8,
    "baseCmMin": 47.99,
    "baseCmTrend": 68.02,
    "baseCtMin": 49.99,
    "baseCtTrend": 69.41,
    "baseEbMin": 48.99,
    "baseEbTrend": 70.8,
    "trendStatus": "up",
    "trendPct": 38.8,
    "blueprintId": 163267,
    "cardTraderUrl": "https://www.cardtrader.com/it/cards/163267-shooting-majestic-star-dragon-secret-rare-dawn-of-majesty",
    "ygoprodeckUrl": "https://ygoprodeck.com/card/shooting-majestic-star-dragon-12012",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/40939228.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/40939228.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/40939228.jpg",
    "cardType": "Synchro Monster",
    "archetype": "Majestic",
    "desc": "\"Majestic Dragon\" + 1+ non-Tuner monsters, including a Dragon Synchro Monster\r\nMust first be Synchro Summoned. Once per turn: You can negate the effects of 1 Effect Monster your opponent controls. This card gains 1 additional attack each Battle Phase for every monster in your GY that is \"Stardust Dragon\" or is a Synchro Monster with \"Stardust Dragon\" in its text. Once per turn, when your opponent activates a card or effect (Quick Effect): You can banish this card (until the End Phase), and if you do, negate the activation, and if you do that, banish that card.",
    "activeListings": 16,
    "notes": "Blueprint CT: #163267 • [IT • Near Mint • 1ª Ed.] 3/16 copie",
    "matchedListings": 3,
    "filterLevel": "IT • Near Mint • 1ª Ed.",
    "updatedAt": "2026-08-18T14:42:53.610Z"
  }
];

const DEFAULT_WANTS = [];

if (typeof module !== 'undefined') {
  module.exports = { DEFAULT_CARDS, DEFAULT_WANTS };
}
