// Dataset iniziale sincronizzato con Listino_Prezzi_Yugioh_Cardmarket_CardTrader.csv
// Arricchito con nomi ufficiali in inglese (englishName), immagini HD (YGOPRODeck) e metadati

const DEFAULT_CARDS = [
  {
    "id": 2,
    "num": 2,
    "name": "Aluber il Giullare di Despia",
    "englishName": "Aluber the Jester of Despia",
    "expansion": "Quarter Century Stampede",
    "code": "RA04-IT038",
    "rarity": "Quarter Century Secret Rare",
    "edition": "Alternate Art / 1ª Ed.",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 45,
    "cmTrend": 51.96,
    "ctMin": 38,
    "ctTrend": 43.97,
    "ebMin": 45.9,
    "ebTrend": 53,
    "baseCmMin": 45,
    "baseCmTrend": 51.96,
    "baseCtMin": 38,
    "baseCtTrend": 43.97,
    "baseEbMin": 45.9,
    "baseEbTrend": 53,
    "trendStatus": "up",
    "trendPct": 1.5,
    "notes": "Mercato Globale / EU - Versione Italiana",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/62962630.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/62962630.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/62962630.jpg",
    "cardType": "Effect Monster",
    "archetype": "Despia",
    "desc": "If this card is Normal or Special Summoned: You can add 1 \"Branded\" Spell/Trap from your Deck to your hand. If a face-up Fusion Monster you control is destroyed by battle, or leaves the field because of an opponent's card effect, while this card is in your GY: You can target 1 Effect Monster your opponent controls; Special Summon this card, and if you do, negate the targeted monster's effects until the end of this turn. You can only use 1 \"Aluber the Jester of Despia\" effect per turn, and only once that turn."
  },
  {
    "id": 3,
    "num": 3,
    "name": "Odino, Padre degli Aesir",
    "englishName": "Odin, Father of the Aesir",
    "expansion": "Storm of Ragnarok",
    "code": "STOR-IT040",
    "rarity": "Ghost Rare",
    "edition": "1ª Edizione",
    "language": "Italiano (ITA)",
    "condition": "Good (GD)",
    "cmMin": 38,
    "cmTrend": 54.7,
    "ctMin": 42,
    "ctTrend": 59.7,
    "ebMin": 38.76,
    "ebTrend": 55.79,
    "baseCmMin": 38,
    "baseCmTrend": 54.7,
    "baseCtMin": 42,
    "baseCtTrend": 59.7,
    "baseEbMin": 38.76,
    "baseEbTrend": 55.79,
    "trendStatus": "up",
    "trendPct": 4.4,
    "notes": "Ghost Rare Vintage 5D's",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/93483212.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/93483212.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/93483212.jpg",
    "cardType": "Synchro Monster",
    "archetype": "Aesir",
    "desc": "1 \"Nordic Ascendant\" Tuner + 2+ non-Tuner monsters\r\nOnce per turn: You can make this card be unaffected by Spell/Trap effects until the end of this turn. Once per turn, during the End Phase, if this face-up card you controlled was destroyed by your opponent's card and sent to your GY this turn: You can banish 1 \"Nordic Ascendant\" Tuner from your GY; Special Summon this card. When Summoned this way: You can draw 1 card."
  },
  {
    "id": 4,
    "num": 4,
    "name": "Thor, Signore degli Aesir",
    "englishName": "Thor, Lord of the Aesir",
    "expansion": "Storm of Ragnarok",
    "code": "STOR-IT038",
    "rarity": "Ultimate Rare",
    "edition": "1ª Edizione",
    "language": "Italiano (ITA)",
    "condition": "Excellent (EX)",
    "cmMin": 16,
    "cmTrend": 24.21,
    "ctMin": 18.5,
    "ctTrend": 25.72,
    "ebMin": 16.32,
    "ebTrend": 24.69,
    "baseCmMin": 16,
    "baseCmTrend": 24.21,
    "baseCtMin": 18.5,
    "baseCtTrend": 25.72,
    "baseEbMin": 16.32,
    "baseEbTrend": 24.69,
    "trendStatus": "up",
    "trendPct": 5.1,
    "notes": "Ultimate Vintage 1ª Ed.",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/30604579.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/30604579.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/30604579.jpg",
    "cardType": "Synchro Monster",
    "archetype": "Aesir",
    "desc": "1 \"Nordic Beast\" Tuner + 2+ non-Tuner monsters\r\nOnce per turn: You can negate the effects of all face-up monsters your opponent currently controls, until the end of this turn. Once per turn, during the End Phase, if this face-up card you controlled was destroyed by your opponent's card and sent to your GY this turn: You can banish 1 \"Nordic Beast\" Tuner from your GY; Special Summon this card. If Summoned this way: Inflict 800 damage to your opponent."
  },
  {
    "id": 5,
    "num": 5,
    "name": "Loki, Signore degli Aesir",
    "englishName": "Loki, Lord of the Aesir",
    "expansion": "Storm of Ragnarok",
    "code": "STOR-IT039",
    "rarity": "Ultimate Rare",
    "edition": "1ª Edizione",
    "language": "Italiano (ITA)",
    "condition": "Excellent (EX)",
    "cmMin": 14,
    "cmTrend": 21.26,
    "ctMin": 15.5,
    "ctTrend": 23.26,
    "ebMin": 14.28,
    "ebTrend": 21.69,
    "baseCmMin": 14,
    "baseCmTrend": 21.26,
    "baseCtMin": 15.5,
    "baseCtTrend": 23.26,
    "baseEbMin": 14.28,
    "baseEbTrend": 21.69,
    "trendStatus": "up",
    "trendPct": 5.2,
    "notes": "Ultimate Vintage 1ª Ed.",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/67098114.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/67098114.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/67098114.jpg",
    "cardType": "Synchro Monster",
    "archetype": "Aesir",
    "desc": "1 \"Nordic Alfar\" Tuner + 2+ non-Tuner monsters\r\nOnce per turn, when your opponent activates a Spell/Trap Card during your Battle Phase (Quick Effect): You can negate the activation, and if you do, destroy it. Once per turn, during the End Phase, if this face-up card you controlled was destroyed by your opponent's card and sent to your GY this turn: You can banish 1 \"Nordic Alfar\" Tuner from your GY; Special Summon this card. When Summoned this way: You can target 1 Trap in your GY; add that target to your hand."
  },
  {
    "id": 6,
    "num": 6,
    "name": "Loki, Signore degli Aesir",
    "englishName": "Loki, Lord of the Aesir",
    "expansion": "Legendary Collection 5D's",
    "code": "LC5D-IT172",
    "rarity": "Secret Rare",
    "edition": "1ª Edizione",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 4.5,
    "cmTrend": 7.75,
    "ctMin": 5,
    "ctTrend": 8.46,
    "ebMin": 4.59,
    "ebTrend": 7.91,
    "baseCmMin": 4.5,
    "baseCmTrend": 7.75,
    "baseCtMin": 5,
    "baseCtTrend": 8.46,
    "baseEbMin": 4.59,
    "baseEbTrend": 7.91,
    "trendStatus": "up",
    "trendPct": 7.2,
    "notes": "LC5D Mega Pack",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/67098114.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/67098114.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/67098114.jpg",
    "cardType": "Synchro Monster",
    "archetype": "Aesir",
    "desc": "1 \"Nordic Alfar\" Tuner + 2+ non-Tuner monsters\r\nOnce per turn, when your opponent activates a Spell/Trap Card during your Battle Phase (Quick Effect): You can negate the activation, and if you do, destroy it. Once per turn, during the End Phase, if this face-up card you controlled was destroyed by your opponent's card and sent to your GY this turn: You can banish 1 \"Nordic Alfar\" Tuner from your GY; Special Summon this card. When Summoned this way: You can target 1 Trap in your GY; add that target to your hand."
  },
  {
    "id": 7,
    "num": 7,
    "name": "Maestro Armatura Ala Nera",
    "englishName": "Blackwing Armor Master",
    "expansion": "Legendary Collection 5D's",
    "code": "LC5D-IT132",
    "rarity": "Secret Rare",
    "edition": "1ª Edizione",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 11,
    "cmTrend": 16.69,
    "ctMin": 12.5,
    "ctTrend": 18.19,
    "ebMin": 11.22,
    "ebTrend": 17.02,
    "baseCmMin": 11,
    "baseCmTrend": 16.69,
    "baseCtMin": 12.5,
    "baseCtTrend": 18.19,
    "baseEbMin": 11.22,
    "baseEbTrend": 17.02,
    "trendStatus": "up",
    "trendPct": 5.2,
    "notes": "LC5D Mega Pack Blackwing",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/69031175.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/69031175.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/69031175.jpg",
    "cardType": "Synchro Monster",
    "archetype": "Blackwing",
    "desc": "1 \"Blackwing\" Tuner + 1 or more non-Tuner monsters\nCannot be destroyed by battle, and you take no battle damage from attacks involving this card. At the end of the Damage Step, if this card attacked a monster: You can place 1 Wedge Counter on that monster (max. 1). You can remove all Wedge Counters from your opponent's monsters; the ATK and DEF of those monsters that had Wedge Counters become 0 until the end of this turn."
  },
  {
    "id": 8,
    "num": 8,
    "name": "Antico Drago Fatato",
    "englishName": "Ancient Fairy Dragon",
    "expansion": "Legendary Collection 5D's",
    "code": "LC5D-IT238",
    "rarity": "Ultra Rare",
    "edition": "1ª Edizione",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 14,
    "cmTrend": 21.83,
    "ctMin": 16,
    "ctTrend": 23.83,
    "ebMin": 14.28,
    "ebTrend": 22.27,
    "baseCmMin": 14,
    "baseCmTrend": 21.83,
    "baseCtMin": 16,
    "baseCtTrend": 23.83,
    "baseEbMin": 14.28,
    "baseEbTrend": 22.27,
    "trendStatus": "up",
    "trendPct": 5.6,
    "notes": "LC5D Mega Pack",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/25862681.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/25862681.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/25862681.jpg",
    "cardType": "Synchro Monster",
    "archetype": "",
    "desc": "1 Tuner + 1+ non-Tuner monsters\r\nDuring your Main Phase: You can Special Summon 1 Level 4 or lower monster from your hand. You cannot conduct your Battle Phase the turn you activate this effect. During your Main Phase: You can destroy as many cards in the Field Zones as possible (min. 1), and if you do, gain 1000 LP, then you can add 1 Field Spell with a different name than the destroyed card(s), from your Deck to your hand. You can only use each effect of \"Ancient Fairy Dragon\" once per turn."
  },
  {
    "id": 9,
    "num": 9,
    "name": "Antico Drago Fatato",
    "englishName": "Ancient Fairy Dragon",
    "expansion": "Quarter Century Stampede",
    "code": "RA04-EN026",
    "rarity": "Quarter Century Secret Rare",
    "edition": "1ª Edizione",
    "language": "Inglese (EN)",
    "condition": "Near Mint",
    "cmMin": 8.5,
    "cmTrend": 13.52,
    "ctMin": 9.5,
    "ctTrend": 14.52,
    "ebMin": 8.67,
    "ebTrend": 13.79,
    "baseCmMin": 8.5,
    "baseCmTrend": 13.52,
    "baseCtMin": 9.5,
    "baseCtTrend": 14.52,
    "baseEbMin": 8.67,
    "baseEbTrend": 13.79,
    "trendStatus": "up",
    "trendPct": 5.9,
    "notes": "QCR 25th Anniversary",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/25862681.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/25862681.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/25862681.jpg",
    "cardType": "Synchro Monster",
    "archetype": "",
    "desc": "1 Tuner + 1+ non-Tuner monsters\r\nDuring your Main Phase: You can Special Summon 1 Level 4 or lower monster from your hand. You cannot conduct your Battle Phase the turn you activate this effect. During your Main Phase: You can destroy as many cards in the Field Zones as possible (min. 1), and if you do, gain 1000 LP, then you can add 1 Field Spell with a different name than the destroyed card(s), from your Deck to your hand. You can only use each effect of \"Ancient Fairy Dragon\" once per turn."
  },
  {
    "id": 10,
    "num": 10,
    "name": "Obelisk il Tormentatore (V.2)",
    "englishName": "Obelisk the Tormentor",
    "expansion": "Quarter Century Stampede",
    "code": "RA04-IT001",
    "rarity": "Quarter Century Secret Rare",
    "edition": "Alternate Art / 1ª Ed.",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 20,
    "cmTrend": 26.63,
    "ctMin": 22,
    "ctTrend": 28.64,
    "ebMin": 20.4,
    "ebTrend": 27.16,
    "baseCmMin": 20,
    "baseCmTrend": 26.63,
    "baseCtMin": 22,
    "baseCtTrend": 28.64,
    "baseEbMin": 20.4,
    "baseEbTrend": 27.16,
    "trendStatus": "up",
    "trendPct": 3.3,
    "notes": "QCR Alt Art Divinità Egizia",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/10000000.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/10000000.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/10000000.jpg",
    "cardType": "Effect Monster",
    "archetype": "Egyptian God",
    "desc": "Requires 3 Tributes to Normal Summon (cannot be Normal Set). This card's Normal Summon cannot be negated. When Normal Summoned, cards and effects cannot be activated. Neither player can target this card with card effects. Once per turn, during the End Phase, if this card was Special Summoned: Send it to the GY. You can Tribute 2 monsters; destroy all monsters your opponent controls. This card cannot declare an attack the turn this effect is activated."
  },
  {
    "id": 11,
    "num": 11,
    "name": "Slifer il Drago del Cielo (V.2)",
    "englishName": "Slifer the Sky Dragon",
    "expansion": "Quarter Century Stampede",
    "code": "RA04-IT002",
    "rarity": "Quarter Century Secret Rare",
    "edition": "Alternate Art / 1ª Ed.",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 25,
    "cmTrend": 31.9,
    "ctMin": 28,
    "ctTrend": 34.9,
    "ebMin": 25.5,
    "ebTrend": 32.54,
    "baseCmMin": 25,
    "baseCmTrend": 31.9,
    "baseCtMin": 28,
    "baseCtTrend": 34.9,
    "baseEbMin": 25.5,
    "baseEbTrend": 32.54,
    "trendStatus": "up",
    "trendPct": 2.8,
    "notes": "QCR Alt Art Divinità Egizia",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/10000020.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/10000020.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/10000020.jpg",
    "cardType": "Effect Monster",
    "archetype": "Egyptian God",
    "desc": "Requires 3 Tributes to Normal Summon (cannot be Normal Set). This card's Normal Summon cannot be negated. When Normal Summoned, cards and effects cannot be activated. Once per turn, during the End Phase, if this card was Special Summoned: Send it to the GY. Gains 1000 ATK/DEF for each card in your hand. If a monster(s) is Normal or Special Summoned to your opponent's field in Attack Position: That monster(s) loses 2000 ATK, then if its ATK has been reduced to 0 as a result, destroy it."
  },
  {
    "id": 12,
    "num": 12,
    "name": "Drago Alato di Ra (V.2)",
    "englishName": "The Winged Dragon of Ra",
    "expansion": "Quarter Century Stampede",
    "code": "RA04-IT003",
    "rarity": "Quarter Century Secret Rare",
    "edition": "Alternate Art / 1ª Ed.",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 30,
    "cmTrend": 37.93,
    "ctMin": 32,
    "ctTrend": 39.93,
    "ebMin": 30.6,
    "ebTrend": 38.69,
    "baseCmMin": 30,
    "baseCmTrend": 37.93,
    "baseCtMin": 32,
    "baseCtTrend": 39.93,
    "baseEbMin": 30.6,
    "baseEbTrend": 38.69,
    "trendStatus": "up",
    "trendPct": 2.6,
    "notes": "QCR Alt Art Divinità Egizia",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/10000010.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/10000010.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/10000010.jpg",
    "cardType": "Effect Monster",
    "archetype": "Egyptian God",
    "desc": "Cannot be Special Summoned. Requires 3 Tributes to Normal Summon (cannot be Normal Set). This card's Normal Summon cannot be negated. When Normal Summoned, other cards and effects cannot be activated. When this card is Normal Summoned: You can pay LP so that you only have 100 left; this card gains ATK/DEF equal to the amount of LP paid. You can pay 1000 LP, then target 1 monster on the field; destroy that target."
  },
  {
    "id": 13,
    "num": 13,
    "name": "Drago Stellare Maestoso Cadente",
    "englishName": "Shooting Majestic Star Dragon",
    "expansion": "Dawn of Majesty",
    "code": "DAMA-IT039",
    "rarity": "Secret Rare",
    "edition": "1ª Edizione",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 8,
    "cmTrend": 12.68,
    "ctMin": 9,
    "ctTrend": 13.67,
    "ebMin": 8.16,
    "ebTrend": 12.93,
    "baseCmMin": 8,
    "baseCmTrend": 12.68,
    "baseCtMin": 9,
    "baseCtTrend": 13.67,
    "baseEbMin": 8.16,
    "baseEbTrend": 12.93,
    "trendStatus": "up",
    "trendPct": 5.8,
    "notes": "Secret DAMA",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/40939228.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/40939228.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/40939228.jpg",
    "cardType": "Synchro Monster",
    "archetype": "Majestic",
    "desc": "\"Majestic Dragon\" + 1+ non-Tuner monsters, including a Dragon Synchro Monster\r\nMust first be Synchro Summoned. Once per turn: You can negate the effects of 1 Effect Monster your opponent controls. This card gains 1 additional attack each Battle Phase for every monster in your GY that is \"Stardust Dragon\" or is a Synchro Monster with \"Stardust Dragon\" in its text. Once per turn, when your opponent activates a card or effect (Quick Effect): You can banish this card (until the End Phase), and if you do, negate the activation, and if you do that, banish that card."
  },
  {
    "id": 14,
    "num": 14,
    "name": "Numero C62: Neo Drago Fotonico Primordiale",
    "englishName": "Number C62: Neo Galaxy-Eyes Prime Photon Dragon",
    "expansion": "Photon Hypernova",
    "code": "PHHY-IT043",
    "rarity": "Ultra Rare",
    "edition": "1ª Edizione",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 1.5,
    "cmTrend": 2.77,
    "ctMin": 2,
    "ctTrend": 3.17,
    "ebMin": 1.53,
    "ebTrend": 2.83,
    "baseCmMin": 1.5,
    "baseCmTrend": 2.77,
    "baseCtMin": 2,
    "baseCtTrend": 3.17,
    "baseEbMin": 1.53,
    "baseEbTrend": 2.83,
    "trendStatus": "up",
    "trendPct": 8.5,
    "notes": "Ultra PHHY",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/48348921.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/48348921.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/48348921.jpg",
    "cardType": "XYZ Monster",
    "archetype": "-Eyes Dragon",
    "desc": "3 Level 8 LIGHT monsters\r\nYou can also Xyz Summon this card by using \"Number 62: Galaxy-Eyes Prime Photon Dragon\" you control. (Transfer its materials to this card.) At the start of your Battle Phase: You can detach 1 material from this card; this card can make up to 3 attacks on monsters during this Battle Phase. If this card has \"Galaxy-Eyes Photon Dragon\" as material, it gains these effects.\r\n● Unaffected by your opponent's monster effects.\r\n● Gains ATK equal to the combined Levels/Ranks of its attached materials x 100."
  },
  {
    "id": 15,
    "num": 15,
    "name": "Aleister l'Invocatore (V.9)",
    "englishName": "Aleister the Invoker",
    "expansion": "Quarter Century Stampede",
    "code": "RA04-IT036",
    "rarity": "Quarter Century Secret Rare",
    "edition": "Alternate Art / 1ª Ed.",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 8,
    "cmTrend": 12.08,
    "ctMin": 9,
    "ctTrend": 13.08,
    "ebMin": 8.16,
    "ebTrend": 12.32,
    "baseCmMin": 8,
    "baseCmTrend": 12.08,
    "baseCtMin": 9,
    "baseCtTrend": 13.08,
    "baseEbMin": 8.16,
    "baseEbTrend": 12.32,
    "trendStatus": "up",
    "trendPct": 5.1,
    "notes": "QCR Alt Art",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/86120751.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/86120751.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/86120751.jpg",
    "cardType": "Effect Monster",
    "archetype": "Invoked",
    "desc": "(Quick Effect): You can send this card from your hand to the GY, then target 1 Fusion Monster you control; it gains 1000 ATK/DEF until the end of this turn. If this card is Normal Summoned or flipped face-up: You can add 1 \"Invocation\" from your Deck to your hand."
  },
  {
    "id": 16,
    "num": 16,
    "name": "Drago Alato di Ra (V.1)",
    "englishName": "The Winged Dragon of Ra",
    "expansion": "Quarter Century Bonanza",
    "code": "RA03-EN003",
    "rarity": "Platinum Secret Rare",
    "edition": "1ª Edizione",
    "language": "Inglese (EN)",
    "condition": "Near Mint",
    "cmMin": 4.5,
    "cmTrend": 6.56,
    "ctMin": 5,
    "ctTrend": 7.06,
    "ebMin": 4.59,
    "ebTrend": 6.69,
    "baseCmMin": 4.5,
    "baseCmTrend": 6.56,
    "baseCtMin": 5,
    "baseCtTrend": 7.06,
    "baseEbMin": 4.59,
    "baseEbTrend": 6.69,
    "trendStatus": "up",
    "trendPct": 4.6,
    "notes": "Platinum Secret Bonanza",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/10000010.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/10000010.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/10000010.jpg",
    "cardType": "Effect Monster",
    "archetype": "Egyptian God",
    "desc": "Cannot be Special Summoned. Requires 3 Tributes to Normal Summon (cannot be Normal Set). This card's Normal Summon cannot be negated. When Normal Summoned, other cards and effects cannot be activated. When this card is Normal Summoned: You can pay LP so that you only have 100 left; this card gains ATK/DEF equal to the amount of LP paid. You can pay 1000 LP, then target 1 monster on the field; destroy that target."
  },
  {
    "id": 17,
    "num": 17,
    "name": "Obelisk il Tormentatore (V.1)",
    "englishName": "Obelisk the Tormentor",
    "expansion": "Quarter Century Bonanza",
    "code": "RA03-EN001",
    "rarity": "Platinum Secret Rare",
    "edition": "1ª Edizione",
    "language": "Inglese (EN)",
    "condition": "Near Mint",
    "cmMin": 4,
    "cmTrend": 5.49,
    "ctMin": 4.5,
    "ctTrend": 5.99,
    "ebMin": 4.08,
    "ebTrend": 5.6,
    "baseCmMin": 4,
    "baseCmTrend": 5.49,
    "baseCtMin": 4.5,
    "baseCtTrend": 5.99,
    "baseEbMin": 4.08,
    "baseEbTrend": 5.6,
    "trendStatus": "up",
    "trendPct": 3.7,
    "notes": "Platinum Secret Bonanza",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/10000000.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/10000000.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/10000000.jpg",
    "cardType": "Effect Monster",
    "archetype": "Egyptian God",
    "desc": "Requires 3 Tributes to Normal Summon (cannot be Normal Set). This card's Normal Summon cannot be negated. When Normal Summoned, cards and effects cannot be activated. Neither player can target this card with card effects. Once per turn, during the End Phase, if this card was Special Summoned: Send it to the GY. You can Tribute 2 monsters; destroy all monsters your opponent controls. This card cannot declare an attack the turn this effect is activated."
  },
  {
    "id": 18,
    "num": 18,
    "name": "Slifer Drago del Cielo (V.1)",
    "englishName": "Slifer the Sky Dragon",
    "expansion": "Quarter Century Bonanza",
    "code": "RA03-EN002",
    "rarity": "Platinum Secret Rare",
    "edition": "1ª Edizione",
    "language": "Inglese (EN)",
    "condition": "Near Mint",
    "cmMin": 4,
    "cmTrend": 5.92,
    "ctMin": 4.5,
    "ctTrend": 6.42,
    "ebMin": 4.08,
    "ebTrend": 6.04,
    "baseCmMin": 4,
    "baseCmTrend": 5.92,
    "baseCtMin": 4.5,
    "baseCtTrend": 6.42,
    "baseEbMin": 4.08,
    "baseEbTrend": 6.04,
    "trendStatus": "up",
    "trendPct": 4.8,
    "notes": "Platinum Secret Bonanza",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/10000020.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/10000020.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/10000020.jpg",
    "cardType": "Effect Monster",
    "archetype": "Egyptian God",
    "desc": "Requires 3 Tributes to Normal Summon (cannot be Normal Set). This card's Normal Summon cannot be negated. When Normal Summoned, cards and effects cannot be activated. Once per turn, during the End Phase, if this card was Special Summoned: Send it to the GY. Gains 1000 ATK/DEF for each card in your hand. If a monster(s) is Normal or Special Summoned to your opponent's field in Attack Position: That monster(s) loses 2000 ATK, then if its ATK has been reduced to 0 as a result, destroy it."
  },
  {
    "id": 19,
    "num": 19,
    "name": "Infernoid Onuncu",
    "englishName": "Infernoid Onuncu",
    "expansion": "Secrets of Eternity",
    "code": "SECE-IT058",
    "rarity": "Ultimate Rare",
    "edition": "1ª Edizione",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 18,
    "cmTrend": 25.63,
    "ctMin": 5.01,
    "ctTrend": 6.77,
    "ebMin": 18.36,
    "ebTrend": 26.14,
    "baseCmMin": 18,
    "baseCmTrend": 25.63,
    "baseCtMin": 5.01,
    "baseCtTrend": 6.77,
    "baseEbMin": 18.36,
    "baseEbTrend": 26.14,
    "trendStatus": "up",
    "trendPct": 4.2,
    "notes": "Ultimate SECE 1st Ed.",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/14799437.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/14799437.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/14799437.jpg",
    "cardType": "Effect Monster",
    "archetype": "Infernoid",
    "desc": "Cannot be Normal Summoned/Set. Must be Special Summoned (from your hand or Graveyard) by banishing 3 \"Infernoid\" monsters from your hand or Graveyard while the total Levels and Ranks of all Effect Monsters you control are 8 or lower, and cannot be Special Summoned by other ways. When this card is Special Summoned: You can destroy all other monsters on the field. Once per turn, during either player's turn, when a Spell/Trap Card or effect is activated: You can Tribute 1 monster; negate the activation, and if you do, banish that card."
  },
  {
    "id": 20,
    "num": 20,
    "name": "Slifer il Drago del Cielo",
    "englishName": "Slifer the Sky Dragon",
    "expansion": "2019 Gold Sarcophagus Tin",
    "code": "TN19-IT008",
    "rarity": "Prismatic Secret Rare",
    "edition": "1ª Edizione",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 5,
    "cmTrend": 7.57,
    "ctMin": 6,
    "ctTrend": 8.07,
    "ebMin": 5.1,
    "ebTrend": 7.72,
    "baseCmMin": 5,
    "baseCmTrend": 7.57,
    "baseCtMin": 6,
    "baseCtTrend": 8.07,
    "baseEbMin": 5.1,
    "baseEbTrend": 7.72,
    "trendStatus": "up",
    "trendPct": 5.1,
    "notes": "Tin 2019 Promo Kazuki Takahashi Art",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/10000020.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/10000020.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/10000020.jpg",
    "cardType": "Effect Monster",
    "archetype": "Egyptian God",
    "desc": "Requires 3 Tributes to Normal Summon (cannot be Normal Set). This card's Normal Summon cannot be negated. When Normal Summoned, cards and effects cannot be activated. Once per turn, during the End Phase, if this card was Special Summoned: Send it to the GY. Gains 1000 ATK/DEF for each card in your hand. If a monster(s) is Normal or Special Summoned to your opponent's field in Attack Position: That monster(s) loses 2000 ATK, then if its ATK has been reduced to 0 as a result, destroy it."
  },
  {
    "id": 21,
    "num": 21,
    "name": "Obelisk il Tormentatore",
    "englishName": "Obelisk the Tormentor",
    "expansion": "2019 Gold Sarcophagus Tin",
    "code": "TN19-IT007",
    "rarity": "Prismatic Secret Rare",
    "edition": "1ª Edizione",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 4.5,
    "cmTrend": 6.95,
    "ctMin": 5.5,
    "ctTrend": 7.45,
    "ebMin": 4.59,
    "ebTrend": 7.09,
    "baseCmMin": 4.5,
    "baseCmTrend": 6.95,
    "baseCtMin": 5.5,
    "baseCtTrend": 7.45,
    "baseEbMin": 4.59,
    "baseEbTrend": 7.09,
    "trendStatus": "up",
    "trendPct": 5.4,
    "notes": "Tin 2019 Promo Kazuki Takahashi Art",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/10000000.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/10000000.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/10000000.jpg",
    "cardType": "Effect Monster",
    "archetype": "Egyptian God",
    "desc": "Requires 3 Tributes to Normal Summon (cannot be Normal Set). This card's Normal Summon cannot be negated. When Normal Summoned, cards and effects cannot be activated. Neither player can target this card with card effects. Once per turn, during the End Phase, if this card was Special Summoned: Send it to the GY. You can Tribute 2 monsters; destroy all monsters your opponent controls. This card cannot declare an attack the turn this effect is activated."
  },
  {
    "id": 22,
    "num": 22,
    "name": "Drago Alato di Ra",
    "englishName": "The Winged Dragon of Ra",
    "expansion": "2019 Gold Sarcophagus Tin",
    "code": "TN19-IT009",
    "rarity": "Prismatic Secret Rare",
    "edition": "1ª Edizione",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 6,
    "cmTrend": 9.05,
    "ctMin": 7,
    "ctTrend": 9.54,
    "ebMin": 6.12,
    "ebTrend": 9.23,
    "baseCmMin": 6,
    "baseCmTrend": 9.05,
    "baseCtMin": 7,
    "baseCtTrend": 9.54,
    "baseEbMin": 6.12,
    "baseEbTrend": 9.23,
    "trendStatus": "up",
    "trendPct": 5.1,
    "notes": "Tin 2019 Promo Kazuki Takahashi Art",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/10000010.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/10000010.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/10000010.jpg",
    "cardType": "Effect Monster",
    "archetype": "Egyptian God",
    "desc": "Cannot be Special Summoned. Requires 3 Tributes to Normal Summon (cannot be Normal Set). This card's Normal Summon cannot be negated. When Normal Summoned, other cards and effects cannot be activated. When this card is Normal Summoned: You can pay LP so that you only have 100 left; this card gains ATK/DEF equal to the amount of LP paid. You can pay 1000 LP, then target 1 monster on the field; destroy that target."
  },
  {
    "id": 23,
    "num": 23,
    "name": "Numero 62: Drago Fotonico Primordiale",
    "englishName": "Number 62: Galaxy-Eyes Prime Photon Dragon",
    "expansion": "Battles of Legend: Light's Revenge",
    "code": "BLLR-IT063",
    "rarity": "Ultra Rare",
    "edition": "1ª Edizione",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 3.5,
    "cmTrend": 5.49,
    "ctMin": 4,
    "ctTrend": 5.99,
    "ebMin": 3.57,
    "ebTrend": 5.6,
    "baseCmMin": 3.5,
    "baseCmTrend": 5.49,
    "baseCtMin": 4,
    "baseCtTrend": 5.99,
    "baseEbMin": 3.57,
    "baseEbTrend": 5.6,
    "trendStatus": "up",
    "trendPct": 5.7,
    "notes": "Ultra BLLR",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/31801517.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/31801517.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/31801517.jpg",
    "cardType": "XYZ Monster",
    "archetype": "Galaxy-Eyes",
    "desc": "2 Level 8 monsters\r\nIf this card battles, during damage calculation (Quick Effect): You can detach 1 material from this card once per battle; this card gains ATK equal to the combined Ranks of all Xyz Monsters currently on the field x 200, during that damage calculation only. If this card in its owner's control is destroyed by an opponent's card effect while it has \"Galaxy-Eyes Photon Dragon\" as Xyz Material: You can Special Summon this card during your 2nd Standby Phase after activation and double its ATK. Any battle damage this card inflicts to your opponent is halved unless it has \"Galaxy-Eyes Photon Dragon\" as Xyz Material."
  },
  {
    "id": 24,
    "num": 24,
    "name": "Numero 89: Diablosis l'Hacker di Menti",
    "englishName": "Number 89: Diablosis the Mind Hacker",
    "expansion": "Battles of Legend: Relentless Revenge",
    "code": "BROL-IT066",
    "rarity": "Ultra Rare",
    "edition": "1ª Edizione",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 1.2,
    "cmTrend": 2.19,
    "ctMin": 1.5,
    "ctTrend": 2.49,
    "ebMin": 1.22,
    "ebTrend": 2.23,
    "baseCmMin": 1.2,
    "baseCmTrend": 2.19,
    "baseCtMin": 1.5,
    "baseCtTrend": 2.49,
    "baseEbMin": 1.22,
    "baseEbTrend": 2.23,
    "trendStatus": "up",
    "trendPct": 8.3,
    "notes": "Ultra BROL (Banned Meta)",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/95474755.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/95474755.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/95474755.jpg",
    "cardType": "XYZ Monster",
    "archetype": "",
    "desc": "2 Level 7 monsters\r\nOnce per turn: You can detach 1 material from this card; look at your opponent's Extra Deck and banish 1 monster from it, face-down. At the end of the Battle Phase, if this card destroyed a monster by battle: You can target 1 card in your opponent's GY; banish it, face-down. If a card your opponent owns and possesses is banished face-down while you control this card (except during the Damage Step): You can banish cards from the top of your opponent's Deck, face-down, equal to their face-down banished cards. You can only use this effect of \"Number 89: Diablosis the Mind Hacker\" once per turn."
  },
  {
    "id": 25,
    "num": 25,
    "name": "Prigione Dimensionale",
    "englishName": "Dimensional Prison",
    "expansion": "Quarter Century Stampede",
    "code": "RA04-IT",
    "rarity": "Platinum Secret Rare",
    "edition": "1ª Edizione",
    "language": "Italiano (ITA)",
    "condition": "Near Mint",
    "cmMin": 2.5,
    "cmTrend": 4.46,
    "ctMin": 3,
    "ctTrend": 4.96,
    "ebMin": 2.55,
    "ebTrend": 4.55,
    "baseCmMin": 2.5,
    "baseCmTrend": 4.46,
    "baseCtMin": 3,
    "baseCtTrend": 4.96,
    "baseEbMin": 2.55,
    "baseEbTrend": 4.55,
    "trendStatus": "up",
    "trendPct": 7.8,
    "notes": "Platinum Secret RA04",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/70342110.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/70342110.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/70342110.jpg",
    "cardType": "Trap Card",
    "archetype": "",
    "desc": "When an opponent's monster declares an attack: Target that attacking monster; banish that target."
  },
  {
    "id": 26,
    "num": 26,
    "name": "Arcidemone Drago Rosso Assalto",
    "englishName": "Red Dragon Archfiend/Assault Mode",
    "expansion": "Crimson Crisis",
    "code": "CRMS-IT004",
    "rarity": "Ultimate Rare",
    "edition": "Unlimited (Non-1ª Ed)",
    "language": "Italiano (ITA)",
    "condition": "Excellent (EX)",
    "cmMin": 18,
    "cmTrend": 28.4,
    "ctMin": 20,
    "ctTrend": 30.39,
    "ebMin": 18.36,
    "ebTrend": 28.97,
    "baseCmMin": 18,
    "baseCmTrend": 28.4,
    "baseCtMin": 20,
    "baseCtTrend": 30.39,
    "baseEbMin": 18.36,
    "baseEbTrend": 28.97,
    "trendStatus": "up",
    "trendPct": 5.8,
    "notes": "Ultimate CRMS Unlimited Vintage",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/77336644.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/77336644.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/77336644.jpg",
    "cardType": "Effect Monster",
    "archetype": "Assault Mode",
    "desc": "This card cannot be Normal Summoned or Set. This card cannot be Special Summoned except with \"Assault Mode Activate\". If this card attacks, destroy all other monsters after damage calculation. When this card on the field is destroyed, you can Special Summon 1 \"Red Dragon Archfiend\" from your Graveyard."
  },
  {
    "id": 27,
    "num": 27,
    "name": "Uria, Signore delle Fiamme Impetuose",
    "englishName": "Uria, Lord of Searing Flames",
    "expansion": "Shadow of Infinity",
    "code": "SOI-IT001",
    "rarity": "Ultimate Rare",
    "edition": "1ª Edizione",
    "language": "Italiano (ITA)",
    "condition": "Excellent (EX)",
    "cmMin": 350,
    "cmTrend": 477.56,
    "ctMin": 380,
    "ctTrend": 517.62,
    "ebMin": 357,
    "ebTrend": 487.11,
    "baseCmMin": 350,
    "baseCmTrend": 477.56,
    "baseCtMin": 380,
    "baseCtTrend": 517.62,
    "baseEbMin": 357,
    "baseEbTrend": 487.11,
    "trendStatus": "up",
    "trendPct": 3.6,
    "notes": "Vintage Grail SOI Ultimate 1ª Edizione",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/6007213.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/6007213.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/6007213.jpg",
    "cardType": "Effect Monster",
    "archetype": "Sacred Beast",
    "desc": "Cannot be Normal Summoned/Set. Must be Special Summoned (from your hand) by sending 3 face-up Traps you control to the GY. Gains 1000 ATK for each Continuous Trap in your GY. Once per turn: You can target 1 Set Spell/Trap your opponent controls; destroy that target. Neither player can activate Spell/Trap Cards in response to this effect's activation."
  },
  {
    "id": 28,
    "num": 28,
    "name": "Hamon, Signore del Tuono Scioccante",
    "englishName": "Hamon, Lord of Striking Thunder",
    "expansion": "Shadow of Infinity",
    "code": "SOI-IT002",
    "rarity": "Ultimate Rare",
    "edition": "1ª Edizione",
    "language": "Italiano (ITA)",
    "condition": "Excellent (EX)",
    "cmMin": 250,
    "cmTrend": 352.42,
    "ctMin": 270,
    "ctTrend": 382.37,
    "ebMin": 255,
    "ebTrend": 359.47,
    "baseCmMin": 250,
    "baseCmTrend": 352.42,
    "baseCtMin": 270,
    "baseCtTrend": 382.37,
    "baseEbMin": 255,
    "baseEbTrend": 359.47,
    "trendStatus": "up",
    "trendPct": 4.1,
    "notes": "Vintage Grail SOI Ultimate 1ª Edizione",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/32491822.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/32491822.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/32491822.jpg",
    "cardType": "Effect Monster",
    "archetype": "Sacred Beast",
    "desc": "Cannot be Normal Summoned/Set. Must be Special Summoned (from your hand) by sending 3 face-up Continuous Spell Cards you control to the Graveyard, and cannot be Special Summoned by other ways. If this card destroys an opponent's monster by battle and sends it to the Graveyard: Inflict 1000 damage to your opponent. While this card is in face-up Defense Position, monsters your opponent controls cannot target monsters for attacks, except this one."
  },
  {
    "id": 29,
    "num": 29,
    "name": "Raviel, il Signore dei Fantasmi",
    "englishName": "Raviel, Lord of Phantasms",
    "expansion": "Shadow of Infinity",
    "code": "SOI-IT003",
    "rarity": "Ultimate Rare",
    "edition": "1ª Edizione",
    "language": "Italiano (ITA)",
    "condition": "Excellent (EX)",
    "cmMin": 280,
    "cmTrend": 425.03,
    "ctMin": 300,
    "ctTrend": 454.85,
    "ebMin": 285.6,
    "ebTrend": 433.53,
    "baseCmMin": 280,
    "baseCmTrend": 425.03,
    "baseCtMin": 300,
    "baseCtTrend": 454.85,
    "baseEbMin": 285.6,
    "baseEbTrend": 433.53,
    "trendStatus": "up",
    "trendPct": 5.2,
    "notes": "Vintage Grail SOI Ultimate 1ª Edizione",
    "imageUrl": "https://images.ygoprodeck.com/images/cards_small/69890967.jpg",
    "imageUrlLarge": "https://images.ygoprodeck.com/images/cards/69890967.jpg",
    "imageUrlCropped": "https://images.ygoprodeck.com/images/cards_cropped/69890967.jpg",
    "cardType": "Effect Monster",
    "archetype": "Sacred Beast",
    "desc": "Cannot be Normal Summoned/Set. Must be Special Summoned (from your hand) by Tributing 3 Fiend-Type monsters, and cannot be Special Summoned by other ways. If your opponent Normal Summons a monster(s): Special Summon 1 \"Phantasm Token\" (Fiend-Type/DARK/Level 1/ATK 1000/DEF 1000) for each monster Summoned, but it cannot declare an attack. Once per turn: You can Tribute 1 monster; this card gains ATK equal to the original ATK of the Tributed monster until the end of this turn."
  }
];

const DEFAULT_WANTS = [
  {
    "id": 101,
    "name": "Drago Bianco Occhi Blu",
    "englishName": "Blue-Eyes White Dragon",
    "expansion": "Leggenda del Drago Bianco Occhi Blu",
    "code": "LOB-I001",
    "rarity": "Ultra Rare",
    "edition": "1ª Edizione",
    "language": "Italiano (ITA)",
    "targetCondition": "Near Mint",
    "targetPrice": 350,
    "cmMin": 320,
    "cmTrend": 390,
    "ctMin": 340,
    "ctTrend": 410,
    "ebMin": 310,
    "ebTrend": 380,
    "baseCmMin": 320,
    "baseCtMin": 340,
    "baseEbMin": 310,
    "trendStatus": "up",
    "trendPct": 9.5,
    "notes": "Sacro Graal LOB 1ª Edizione Italiano"
  },
  {
    "id": 102,
    "name": "S:P Little Knight",
    "englishName": "S:P Little Knight",
    "expansion": "Age of Overlord",
    "code": "AGOV-EN043",
    "rarity": "Secret Rare",
    "edition": "1ª Edizione",
    "language": "Inglese (EN)",
    "targetCondition": "Near Mint",
    "targetPrice": 70,
    "cmMin": 68,
    "cmTrend": 78,
    "ctMin": 72,
    "ctTrend": 82,
    "ebMin": 69,
    "ebTrend": 80,
    "baseCmMin": 68,
    "baseCtMin": 72,
    "baseEbMin": 69,
    "trendStatus": "down",
    "trendPct": -4.5,
    "notes": "Staple meta universale"
  },
  {
    "id": 103,
    "name": "Mago Nero",
    "englishName": "Dark Magician",
    "expansion": "Dark Duel Stories",
    "code": "DDS-002",
    "rarity": "Prismatic Secret Rare",
    "edition": "Promo GameBoy",
    "language": "Inglese (EN)",
    "targetCondition": "Excellent (EX)",
    "targetPrice": 450,
    "cmMin": 480,
    "cmTrend": 580,
    "ctMin": 490,
    "ctTrend": 600,
    "ebMin": 460,
    "ebTrend": 570,
    "baseCmMin": 480,
    "baseCtMin": 490,
    "baseEbMin": 460,
    "trendStatus": "up",
    "trendPct": 12,
    "notes": "DDS Promo Vintage"
  },
  {
    "id": 104,
    "name": "Accesscode Talker",
    "englishName": "Accesscode Talker",
    "expansion": "Eternity Code",
    "code": "ETCO-EN046",
    "rarity": "Secret Rare",
    "edition": "1ª Edizione",
    "language": "Inglese (EN)",
    "targetCondition": "Near Mint",
    "targetPrice": 28,
    "cmMin": 24.5,
    "cmTrend": 31,
    "ctMin": 26,
    "ctTrend": 33,
    "ebMin": 25,
    "ebTrend": 32,
    "baseCmMin": 24.5,
    "baseCtMin": 26,
    "baseEbMin": 25,
    "trendStatus": "stable",
    "trendPct": 1,
    "notes": "ETCO 1st Ed. Boss monster"
  },
  {
    "id": 105,
    "name": "Baronne de Fleur",
    "englishName": "Baronne de Fleur",
    "expansion": "Legendary Duelists: Synchro Storm",
    "code": "LED8-EN024",
    "rarity": "Ultra Rare",
    "edition": "1ª Edizione",
    "language": "Inglese (EN)",
    "targetCondition": "Near Mint",
    "targetPrice": 15,
    "cmMin": 12,
    "cmTrend": 16.5,
    "ctMin": 13.5,
    "ctTrend": 17,
    "ebMin": 12.5,
    "ebTrend": 16,
    "baseCmMin": 12,
    "baseCtMin": 13.5,
    "baseEbMin": 12.5,
    "trendStatus": "down",
    "trendPct": -8,
    "notes": "Synchro staple"
  }
];

if (typeof module !== 'undefined') {
  module.exports = { DEFAULT_CARDS, DEFAULT_WANTS };
}
