// Dataset iniziale sincronizzato con Listino_Prezzi_Yugioh_Cardmarket_CardTrader.csv
// Arricchito con nomi ufficiali in inglese (englishName) per query perfette su Cardmarket, CardTrader ed eBay

const DEFAULT_CARDS = [
  {
    id: 1,
    num: 1,
    name: "Aluber the Jester of Despia",
    englishName: "Aluber the Jester of Despia",
    expansion: "Quarter Century Stampede",
    code: "RA04-EN038",
    rarity: "Quarter Century Secret Rare",
    edition: "Alternate Art / 1ª Ed.",
    language: "Inglese (EN)",
    condition: "Near Mint",
    cmMin: 42.00,
    cmTrend: 48.50,
    ctMin: 35.89,
    ctTrend: 41.50,
    ebMin: 38.00,
    ebTrend: 46.00,
    baseCmMin: 42.00,
    baseCmTrend: 48.50,
    baseCtMin: 35.89,
    baseCtTrend: 41.50,
    baseEbMin: 38.00,
    baseEbTrend: 46.00,
    trendStatus: "up",
    trendPct: 8.5,
    notes: "Mercato Globale / EU - QCR Alt Art"
  },
  {
    id: 2,
    num: 2,
    name: "Aluber il Giullare di Despia",
    englishName: "Aluber the Jester of Despia",
    expansion: "Quarter Century Stampede",
    code: "RA04-IT038",
    rarity: "Quarter Century Secret Rare",
    edition: "Alternate Art / 1ª Ed.",
    language: "Italiano (ITA)",
    condition: "Near Mint",
    cmMin: 45.00,
    cmTrend: 52.00,
    ctMin: 38.00,
    ctTrend: 44.00,
    ebMin: 40.00,
    ebTrend: 49.00,
    baseCmMin: 45.00,
    baseCmTrend: 52.00,
    baseCtMin: 38.00,
    baseCtTrend: 44.00,
    baseEbMin: 40.00,
    baseEbTrend: 49.00,
    trendStatus: "up",
    trendPct: 10.2,
    notes: "Mercato Globale / EU - Versione Italiana"
  },
  {
    id: 3,
    num: 3,
    name: "Odino, Padre degli Aesir",
    englishName: "Odin, Father of the Aesir",
    expansion: "Storm of Ragnarok",
    code: "STOR-IT040",
    rarity: "Ghost Rare",
    edition: "1ª Edizione",
    language: "Italiano (ITA)",
    condition: "Good (GD)",
    cmMin: 38.00,
    cmTrend: 55.00,
    ctMin: 42.00,
    ctTrend: 60.00,
    ebMin: 40.00,
    ebTrend: 58.00,
    baseCmMin: 38.00,
    baseCmTrend: 55.00,
    baseCtMin: 42.00,
    baseCtTrend: 60.00,
    baseEbMin: 40.00,
    baseEbTrend: 58.00,
    trendStatus: "up",
    trendPct: 15.0,
    notes: "Ghost Rare Vintage 5D's"
  },
  {
    id: 4,
    num: 4,
    name: "Thor, Signore degli Aesir",
    englishName: "Thor, Lord of the Aesir",
    expansion: "Storm of Ragnarok",
    code: "STOR-IT038",
    rarity: "Ultimate Rare",
    edition: "1ª Edizione",
    language: "Italiano (ITA)",
    condition: "Excellent (EX)",
    cmMin: 16.00,
    cmTrend: 24.50,
    ctMin: 18.50,
    ctTrend: 26.00,
    ebMin: 18.00,
    ebTrend: 25.00,
    baseCmMin: 16.00,
    baseCmTrend: 24.50,
    baseCtMin: 18.50,
    baseCtTrend: 26.00,
    baseEbMin: 18.00,
    baseEbTrend: 25.00,
    trendStatus: "up",
    trendPct: 6.4,
    notes: "Ultimate Vintage 1ª Ed."
  },
  {
    id: 5,
    num: 5,
    name: "Loki, Signore degli Aesir",
    englishName: "Loki, Lord of the Aesir",
    expansion: "Storm of Ragnarok",
    code: "STOR-IT039",
    rarity: "Ultimate Rare",
    edition: "1ª Edizione",
    language: "Italiano (ITA)",
    condition: "Excellent (EX)",
    cmMin: 14.00,
    cmTrend: 21.00,
    ctMin: 15.50,
    ctTrend: 23.00,
    ebMin: 15.00,
    ebTrend: 22.00,
    baseCmMin: 14.00,
    baseCmTrend: 21.00,
    baseCtMin: 15.50,
    baseCtTrend: 23.00,
    baseEbMin: 15.00,
    baseEbTrend: 22.00,
    trendStatus: "stable",
    trendPct: 1.2,
    notes: "Ultimate Vintage 1ª Ed."
  },
  {
    id: 6,
    num: 6,
    name: "Loki, Signore degli Aesir",
    englishName: "Loki, Lord of the Aesir",
    expansion: "Legendary Collection 5D's",
    code: "LC5D-IT172",
    rarity: "Secret Rare",
    edition: "1ª Edizione",
    language: "Italiano (ITA)",
    condition: "Near Mint",
    cmMin: 4.50,
    cmTrend: 7.80,
    ctMin: 5.00,
    ctTrend: 8.50,
    ebMin: 5.00,
    ebTrend: 8.00,
    baseCmMin: 4.50,
    baseCmTrend: 7.80,
    baseCtMin: 5.00,
    baseCtTrend: 8.50,
    baseEbMin: 5.00,
    baseEbTrend: 8.00,
    trendStatus: "stable",
    trendPct: 0.5,
    notes: "LC5D Mega Pack"
  },
  {
    id: 7,
    num: 7,
    name: "Maestro Armatura Ala Nera",
    englishName: "Blackwing Armor Master",
    expansion: "Legendary Collection 5D's",
    code: "LC5D-IT132",
    rarity: "Secret Rare",
    edition: "1ª Edizione",
    language: "Italiano (ITA)",
    condition: "Near Mint",
    cmMin: 11.00,
    cmTrend: 16.50,
    ctMin: 12.50,
    ctTrend: 18.00,
    ebMin: 12.00,
    ebTrend: 17.50,
    baseCmMin: 11.00,
    baseCmTrend: 16.50,
    baseCtMin: 12.50,
    baseCtTrend: 18.00,
    baseEbMin: 12.00,
    baseEbTrend: 17.50,
    trendStatus: "up",
    trendPct: 5.8,
    notes: "LC5D Mega Pack Blackwing"
  },
  {
    id: 8,
    num: 8,
    name: "Antico Drago Fatato",
    englishName: "Ancient Fairy Dragon",
    expansion: "Legendary Collection 5D's",
    code: "LC5D-IT238",
    rarity: "Ultra Rare",
    edition: "1ª Edizione",
    language: "Italiano (ITA)",
    condition: "Near Mint",
    cmMin: 14.00,
    cmTrend: 22.00,
    ctMin: 16.00,
    ctTrend: 24.00,
    ebMin: 15.00,
    ebTrend: 23.50,
    baseCmMin: 14.00,
    baseCmTrend: 22.00,
    baseCtMin: 16.00,
    baseCtTrend: 24.00,
    baseEbMin: 15.00,
    baseEbTrend: 23.50,
    trendStatus: "up",
    trendPct: 7.2,
    notes: "LC5D Mega Pack"
  },
  {
    id: 9,
    num: 9,
    name: "Antico Drago Fatato",
    englishName: "Ancient Fairy Dragon",
    expansion: "Quarter Century Stampede",
    code: "RA04-EN026",
    rarity: "Quarter Century Secret Rare",
    edition: "1ª Edizione",
    language: "Inglese (EN)",
    condition: "Near Mint",
    cmMin: 8.50,
    cmTrend: 13.50,
    ctMin: 9.50,
    ctTrend: 14.50,
    ebMin: 9.00,
    ebTrend: 14.00,
    baseCmMin: 8.50,
    baseCmTrend: 13.50,
    baseCtMin: 9.50,
    baseCtTrend: 14.50,
    baseEbMin: 9.00,
    baseEbTrend: 14.00,
    trendStatus: "down",
    trendPct: -3.8,
    notes: "QCR 25th Anniversary"
  },
  {
    id: 10,
    num: 10,
    name: "Obelisk il Tormentatore (V.2)",
    englishName: "Obelisk the Tormentor",
    expansion: "Quarter Century Stampede",
    code: "RA04-IT001",
    rarity: "Quarter Century Secret Rare",
    edition: "Alternate Art / 1ª Ed.",
    language: "Italiano (ITA)",
    condition: "Near Mint",
    cmMin: 20.00,
    cmTrend: 27.00,
    ctMin: 22.00,
    ctTrend: 29.00,
    ebMin: 21.00,
    ebTrend: 28.00,
    baseCmMin: 20.00,
    baseCmTrend: 27.00,
    baseCtMin: 22.00,
    baseCtTrend: 29.00,
    baseEbMin: 21.00,
    baseEbTrend: 28.00,
    trendStatus: "up",
    trendPct: 4.5,
    notes: "QCR Alt Art Divinità Egizia"
  },
  {
    id: 11,
    num: 11,
    name: "Slifer il Drago del Cielo (V.2)",
    englishName: "Slifer the Sky Dragon",
    expansion: "Quarter Century Stampede",
    code: "RA04-IT002",
    rarity: "Quarter Century Secret Rare",
    edition: "Alternate Art / 1ª Ed.",
    language: "Italiano (ITA)",
    condition: "Near Mint",
    cmMin: 25.00,
    cmTrend: 32.00,
    ctMin: 28.00,
    ctTrend: 35.00,
    ebMin: 27.00,
    ebTrend: 34.00,
    baseCmMin: 25.00,
    baseCmTrend: 32.00,
    baseCtMin: 28.00,
    baseCtTrend: 35.00,
    baseEbMin: 27.00,
    baseEbTrend: 34.00,
    trendStatus: "up",
    trendPct: 6.8,
    notes: "QCR Alt Art Divinità Egizia"
  },
  {
    id: 12,
    num: 12,
    name: "Drago Alato di Ra (V.2)",
    englishName: "The Winged Dragon of Ra",
    expansion: "Quarter Century Stampede",
    code: "RA04-IT003",
    rarity: "Quarter Century Secret Rare",
    edition: "Alternate Art / 1ª Ed.",
    language: "Italiano (ITA)",
    condition: "Near Mint",
    cmMin: 30.00,
    cmTrend: 38.00,
    ctMin: 32.00,
    ctTrend: 40.00,
    ebMin: 31.00,
    ebTrend: 39.00,
    baseCmMin: 30.00,
    baseCmTrend: 38.00,
    baseCtMin: 32.00,
    baseCtTrend: 40.00,
    baseEbMin: 31.00,
    baseEbTrend: 39.00,
    trendStatus: "up",
    trendPct: 8.0,
    notes: "QCR Alt Art Divinità Egizia"
  },
  {
    id: 13,
    num: 13,
    name: "Drago Stellare Maestoso Cadente",
    englishName: "Shooting Majestic Star Dragon",
    expansion: "Dawn of Majesty",
    code: "DAMA-IT039",
    rarity: "Secret Rare",
    edition: "1ª Edizione",
    language: "Italiano (ITA)",
    condition: "Near Mint",
    cmMin: 8.00,
    cmTrend: 12.50,
    ctMin: 9.00,
    ctTrend: 13.50,
    ebMin: 8.50,
    ebTrend: 13.00,
    baseCmMin: 8.00,
    baseCmTrend: 12.50,
    baseCtMin: 9.00,
    baseCtTrend: 13.50,
    baseEbMin: 8.50,
    baseEbTrend: 13.00,
    trendStatus: "stable",
    trendPct: 0.0,
    notes: "Secret DAMA"
  },
  {
    id: 14,
    num: 14,
    name: "Numero C62: Neo Drago Fotonico Primordiale",
    englishName: "Number C62: Neo Galaxy-Eyes Prime Photon Dragon",
    expansion: "Photon Hypernova",
    code: "PHHY-IT043",
    rarity: "Ultra Rare",
    edition: "1ª Edizione",
    language: "Italiano (ITA)",
    condition: "Near Mint",
    cmMin: 1.50,
    cmTrend: 2.80,
    ctMin: 2.00,
    ctTrend: 3.20,
    ebMin: 2.00,
    ebTrend: 3.00,
    baseCmMin: 1.50,
    baseCmTrend: 2.80,
    baseCtMin: 2.00,
    baseCtTrend: 3.20,
    baseEbMin: 2.00,
    baseEbTrend: 3.00,
    trendStatus: "down",
    trendPct: -5.5,
    notes: "Ultra PHHY"
  },
  {
    id: 15,
    num: 15,
    name: "Aleister l'Invocatore (V.9)",
    englishName: "Aleister the Invoker",
    expansion: "Quarter Century Stampede",
    code: "RA04-IT036",
    rarity: "Quarter Century Secret Rare",
    edition: "Alternate Art / 1ª Ed.",
    language: "Italiano (ITA)",
    condition: "Near Mint",
    cmMin: 8.00,
    cmTrend: 12.00,
    ctMin: 9.00,
    ctTrend: 13.00,
    ebMin: 8.50,
    ebTrend: 12.50,
    baseCmMin: 8.00,
    baseCmTrend: 12.00,
    baseCtMin: 9.00,
    baseCtTrend: 13.00,
    baseEbMin: 8.50,
    baseEbTrend: 12.50,
    trendStatus: "stable",
    trendPct: 1.0,
    notes: "QCR Alt Art"
  },
  {
    id: 16,
    num: 16,
    name: "Drago Alato di Ra (V.1)",
    englishName: "The Winged Dragon of Ra",
    expansion: "Quarter Century Bonanza",
    code: "RA03-EN003",
    rarity: "Platinum Secret Rare",
    edition: "1ª Edizione",
    language: "Inglese (EN)",
    condition: "Near Mint",
    cmMin: 4.50,
    cmTrend: 6.50,
    ctMin: 5.00,
    ctTrend: 7.00,
    ebMin: 5.00,
    ebTrend: 7.00,
    baseCmMin: 4.50,
    baseCmTrend: 6.50,
    baseCtMin: 5.00,
    baseCtTrend: 7.00,
    baseEbMin: 5.00,
    baseEbTrend: 7.00,
    trendStatus: "down",
    trendPct: -4.2,
    notes: "Platinum Secret Bonanza"
  },
  {
    id: 17,
    num: 17,
    name: "Obelisk il Tormentatore (V.1)",
    englishName: "Obelisk the Tormentor",
    expansion: "Quarter Century Bonanza",
    code: "RA03-EN001",
    rarity: "Platinum Secret Rare",
    edition: "1ª Edizione",
    language: "Inglese (EN)",
    condition: "Near Mint",
    cmMin: 4.00,
    cmTrend: 5.50,
    ctMin: 4.50,
    ctTrend: 6.00,
    ebMin: 4.50,
    ebTrend: 6.00,
    baseCmMin: 4.00,
    baseCmTrend: 5.50,
    baseCtMin: 4.50,
    baseCtTrend: 6.00,
    baseEbMin: 4.50,
    baseEbTrend: 6.00,
    trendStatus: "stable",
    trendPct: -1.0,
    notes: "Platinum Secret Bonanza"
  },
  {
    id: 18,
    num: 18,
    name: "Slifer Drago del Cielo (V.1)",
    englishName: "Slifer the Sky Dragon",
    expansion: "Quarter Century Bonanza",
    code: "RA03-EN002",
    rarity: "Platinum Secret Rare",
    edition: "1ª Edizione",
    language: "Inglese (EN)",
    condition: "Near Mint",
    cmMin: 4.00,
    cmTrend: 6.00,
    ctMin: 4.50,
    ctTrend: 6.50,
    ebMin: 4.50,
    ebTrend: 6.50,
    baseCmMin: 4.00,
    baseCmTrend: 6.00,
    baseCtMin: 4.50,
    baseCtTrend: 6.50,
    baseEbMin: 4.50,
    baseEbTrend: 6.50,
    trendStatus: "stable",
    trendPct: 0.0,
    notes: "Platinum Secret Bonanza"
  },
  {
    id: 19,
    num: 19,
    name: "Infernoid Onuncu",
    englishName: "Infernoid Onuncu",
    expansion: "Secrets of Eternity",
    code: "SECE-IT058",
    rarity: "Ultimate Rare",
    edition: "1ª Edizione",
    language: "Italiano (ITA)",
    condition: "Near Mint",
    cmMin: 8.00,
    cmTrend: 10.50,
    ctMin: 8.50,
    ctTrend: 11.00,
    ebMin: 9.00,
    ebTrend: 11.50,
    baseCmMin: 8.00,
    baseCmTrend: 10.50,
    baseCtMin: 8.50,
    baseCtTrend: 11.00,
    baseEbMin: 9.00,
    baseEbTrend: 11.50,
    trendStatus: "down",
    trendPct: -12.5,
    notes: "Ultimate SECE 1st Ed."
  },
  {
    id: 20,
    num: 20,
    name: "Slifer il Drago del Cielo",
    englishName: "Slifer the Sky Dragon",
    expansion: "2019 Gold Sarcophagus Tin",
    code: "TN19-IT008",
    rarity: "Prismatic Secret Rare",
    edition: "1ª Edizione",
    language: "Italiano (ITA)",
    condition: "Near Mint",
    cmMin: 5.00,
    cmTrend: 7.50,
    ctMin: 6.00,
    ctTrend: 8.00,
    ebMin: 5.50,
    ebTrend: 8.00,
    baseCmMin: 5.00,
    baseCmTrend: 7.50,
    baseCtMin: 6.00,
    baseCtTrend: 8.00,
    baseEbMin: 5.50,
    baseEbTrend: 8.00,
    trendStatus: "up",
    trendPct: 4.0,
    notes: "Tin 2019 Promo Kazuki Takahashi Art"
  },
  {
    id: 21,
    num: 21,
    name: "Obelisk il Tormentatore",
    englishName: "Obelisk the Tormentor",
    expansion: "2019 Gold Sarcophagus Tin",
    code: "TN19-IT007",
    rarity: "Prismatic Secret Rare",
    edition: "1ª Edizione",
    language: "Italiano (ITA)",
    condition: "Near Mint",
    cmMin: 4.50,
    cmTrend: 7.00,
    ctMin: 5.50,
    ctTrend: 7.50,
    ebMin: 5.00,
    ebTrend: 7.50,
    baseCmMin: 4.50,
    baseCmTrend: 7.00,
    baseCtMin: 5.50,
    baseCtTrend: 7.50,
    baseEbMin: 5.00,
    baseEbTrend: 7.50,
    trendStatus: "stable",
    trendPct: 1.5,
    notes: "Tin 2019 Promo Kazuki Takahashi Art"
  },
  {
    id: 22,
    num: 22,
    name: "Drago Alato di Ra",
    englishName: "The Winged Dragon of Ra",
    expansion: "2019 Gold Sarcophagus Tin",
    code: "TN19-IT009",
    rarity: "Prismatic Secret Rare",
    edition: "1ª Edizione",
    language: "Italiano (ITA)",
    condition: "Near Mint",
    cmMin: 6.00,
    cmTrend: 9.00,
    ctMin: 7.00,
    ctTrend: 9.50,
    ebMin: 6.50,
    ebTrend: 9.50,
    baseCmMin: 6.00,
    baseCmTrend: 9.00,
    baseCtMin: 7.00,
    baseCtTrend: 9.50,
    baseEbMin: 6.50,
    baseEbTrend: 9.50,
    trendStatus: "up",
    trendPct: 5.0,
    notes: "Tin 2019 Promo Kazuki Takahashi Art"
  },
  {
    id: 23,
    num: 23,
    name: "Numero 62: Drago Fotonico Primordiale",
    englishName: "Number 62: Galaxy-Eyes Prime Photon Dragon",
    expansion: "Battles of Legend: Light's Revenge",
    code: "BLLR-IT063",
    rarity: "Ultra Rare",
    edition: "1ª Edizione",
    language: "Italiano (ITA)",
    condition: "Near Mint",
    cmMin: 3.50,
    cmTrend: 5.50,
    ctMin: 4.00,
    ctTrend: 6.00,
    ebMin: 4.00,
    ebTrend: 5.80,
    baseCmMin: 3.50,
    baseCmTrend: 5.50,
    baseCtMin: 4.00,
    baseCtTrend: 6.00,
    baseEbMin: 4.00,
    baseEbTrend: 5.80,
    trendStatus: "down",
    trendPct: -2.5,
    notes: "Ultra BLLR"
  },
  {
    id: 24,
    num: 24,
    name: "Numero 89: Diablosis l'Hacker di Menti",
    englishName: "Number 89: Diablosis the Mind Hacker",
    expansion: "Battles of Legend: Relentless Revenge",
    code: "BROL-IT066",
    rarity: "Ultra Rare",
    edition: "1ª Edizione",
    language: "Italiano (ITA)",
    condition: "Near Mint",
    cmMin: 1.20,
    cmTrend: 2.20,
    ctMin: 1.50,
    ctTrend: 2.50,
    ebMin: 1.50,
    ebTrend: 2.40,
    baseCmMin: 1.20,
    baseCmTrend: 2.20,
    baseCtMin: 1.50,
    baseCtTrend: 2.50,
    baseEbMin: 1.50,
    baseEbTrend: 2.40,
    trendStatus: "down",
    trendPct: -6.0,
    notes: "Ultra BROL (Banned Meta)"
  },
  {
    id: 25,
    num: 25,
    name: "Prigione Dimensionale",
    englishName: "Dimensional Prison",
    expansion: "Quarter Century Stampede",
    code: "RA04-IT",
    rarity: "Platinum Secret Rare",
    edition: "1ª Edizione",
    language: "Italiano (ITA)",
    condition: "Near Mint",
    cmMin: 2.50,
    cmTrend: 4.50,
    ctMin: 3.00,
    ctTrend: 5.00,
    ebMin: 3.00,
    ebTrend: 4.80,
    baseCmMin: 2.50,
    baseCmTrend: 4.50,
    baseCtMin: 3.00,
    baseCtTrend: 5.00,
    baseEbMin: 3.00,
    baseEbTrend: 4.80,
    trendStatus: "stable",
    trendPct: 0.0,
    notes: "Platinum Secret RA04"
  },
  {
    id: 26,
    num: 26,
    name: "Arcidemone Drago Rosso Assalto",
    englishName: "Red Dragon Archfiend/Assault Mode",
    expansion: "Crimson Crisis",
    code: "CRMS-IT004",
    rarity: "Ultimate Rare",
    edition: "Unlimited (Non-1ª Ed)",
    language: "Italiano (ITA)",
    condition: "Excellent (EX)",
    cmMin: 18.00,
    cmTrend: 28.00,
    ctMin: 20.00,
    ctTrend: 30.00,
    ebMin: 20.00,
    ebTrend: 29.50,
    baseCmMin: 18.00,
    baseCmTrend: 28.00,
    baseCtMin: 20.00,
    baseCtTrend: 30.00,
    baseEbMin: 20.00,
    baseEbTrend: 29.50,
    trendStatus: "up",
    trendPct: 8.5,
    notes: "Ultimate CRMS Unlimited Vintage"
  },
  {
    id: 27,
    num: 27,
    name: "Uria, Signore delle Fiamme Ardenti",
    englishName: "Uria, Lord of Searing Flames",
    expansion: "Shadow of Infinity",
    code: "SOI-IT001",
    rarity: "Ultimate Rare",
    edition: "1ª Edizione",
    language: "Italiano (ITA)",
    condition: "Excellent (EX)",
    cmMin: 350.00,
    cmTrend: 480.00,
    ctMin: 380.00,
    ctTrend: 520.00,
    ebMin: 390.00,
    ebTrend: 510.00,
    baseCmMin: 350.00,
    baseCmTrend: 480.00,
    baseCtMin: 380.00,
    baseCtTrend: 520.00,
    baseEbMin: 390.00,
    baseEbTrend: 510.00,
    trendStatus: "up",
    trendPct: 18.5,
    notes: "Vintage Grail SOI Ultimate 1ª Edizione"
  },
  {
    id: 28,
    num: 28,
    name: "Hamon, Signore del Tuono Fragoroso",
    englishName: "Hamon, Lord of Striking Thunder",
    expansion: "Shadow of Infinity",
    code: "SOI-IT002",
    rarity: "Ultimate Rare",
    edition: "1ª Edizione",
    language: "Italiano (ITA)",
    condition: "Excellent (EX)",
    cmMin: 250.00,
    cmTrend: 350.00,
    ctMin: 270.00,
    ctTrend: 380.00,
    ebMin: 275.00,
    ebTrend: 375.00,
    baseCmMin: 250.00,
    baseCmTrend: 350.00,
    baseCtMin: 270.00,
    baseCtTrend: 380.00,
    baseEbMin: 275.00,
    baseEbTrend: 375.00,
    trendStatus: "up",
    trendPct: 14.2,
    notes: "Vintage Grail SOI Ultimate 1ª Edizione"
  },
  {
    id: 29,
    num: 29,
    name: "Raviel, il Signore dei Fantasmi",
    englishName: "Raviel, Lord of Phantasms",
    expansion: "Shadow of Infinity",
    code: "SOI-IT003",
    rarity: "Ultimate Rare",
    edition: "1ª Edizione",
    language: "Italiano (ITA)",
    condition: "Excellent (EX)",
    cmMin: 280.00,
    cmTrend: 420.00,
    ctMin: 300.00,
    ctTrend: 450.00,
    ebMin: 310.00,
    ebTrend: 440.00,
    baseCmMin: 280.00,
    baseCmTrend: 420.00,
    baseCtMin: 300.00,
    baseCtTrend: 450.00,
    baseEbMin: 310.00,
    baseEbTrend: 440.00,
    trendStatus: "up",
    trendPct: 16.0,
    notes: "Vintage Grail SOI Ultimate 1ª Edizione"
  }
];

const DEFAULT_WANTS = [
  {
    id: 101,
    name: "Drago Bianco Occhi Blu",
    englishName: "Blue-Eyes White Dragon",
    expansion: "Leggenda del Drago Bianco Occhi Blu",
    code: "LOB-I001",
    rarity: "Ultra Rare",
    edition: "1ª Edizione",
    language: "Italiano (ITA)",
    targetCondition: "Near Mint",
    targetPrice: 350.00,
    cmMin: 320.00,
    cmTrend: 390.00,
    ctMin: 340.00,
    ctTrend: 410.00,
    ebMin: 310.00,
    ebTrend: 380.00,
    baseCmMin: 320.00,
    baseCtMin: 340.00,
    baseEbMin: 310.00,
    trendStatus: "up",
    trendPct: 9.5,
    notes: "Sacro Graal LOB 1ª Edizione Italiano"
  },
  {
    id: 102,
    name: "S:P Little Knight",
    englishName: "S:P Little Knight",
    expansion: "Age of Overlord",
    code: "AGOV-EN043",
    rarity: "Secret Rare",
    edition: "1ª Edizione",
    language: "Inglese (EN)",
    targetCondition: "Near Mint",
    targetPrice: 70.00,
    cmMin: 68.00,
    cmTrend: 78.00,
    ctMin: 72.00,
    ctTrend: 82.00,
    ebMin: 69.00,
    ebTrend: 80.00,
    baseCmMin: 68.00,
    baseCtMin: 72.00,
    baseEbMin: 69.00,
    trendStatus: "down",
    trendPct: -4.5,
    notes: "Staple meta universale"
  },
  {
    id: 103,
    name: "Mago Nero",
    englishName: "Dark Magician",
    expansion: "Dark Duel Stories",
    code: "DDS-002",
    rarity: "Prismatic Secret Rare",
    edition: "Promo GameBoy",
    language: "Inglese (EN)",
    targetCondition: "Excellent (EX)",
    targetPrice: 450.00,
    cmMin: 480.00,
    cmTrend: 580.00,
    ctMin: 490.00,
    ctTrend: 600.00,
    ebMin: 460.00,
    ebTrend: 570.00,
    baseCmMin: 480.00,
    baseCtMin: 490.00,
    baseEbMin: 460.00,
    trendStatus: "up",
    trendPct: 12.0,
    notes: "DDS Promo Vintage"
  },
  {
    id: 104,
    name: "Accesscode Talker",
    englishName: "Accesscode Talker",
    expansion: "Eternity Code",
    code: "ETCO-EN046",
    rarity: "Secret Rare",
    edition: "1ª Edizione",
    language: "Inglese (EN)",
    targetCondition: "Near Mint",
    targetPrice: 28.00,
    cmMin: 24.50,
    cmTrend: 31.00,
    ctMin: 26.00,
    ctTrend: 33.00,
    ebMin: 25.00,
    ebTrend: 32.00,
    baseCmMin: 24.50,
    baseCtMin: 26.00,
    baseEbMin: 25.00,
    trendStatus: "stable",
    trendPct: 1.0,
    notes: "ETCO 1st Ed. Boss monster"
  },
  {
    id: 105,
    name: "Baronne de Fleur",
    englishName: "Baronne de Fleur",
    expansion: "Legendary Duelists: Synchro Storm",
    code: "LED8-EN024",
    rarity: "Ultra Rare",
    edition: "1ª Edizione",
    language: "Inglese (EN)",
    targetCondition: "Near Mint",
    targetPrice: 15.00,
    cmMin: 12.00,
    cmTrend: 16.50,
    ctMin: 13.50,
    ctTrend: 17.00,
    ebMin: 12.50,
    ebTrend: 16.00,
    baseCmMin: 12.00,
    baseCtMin: 13.50,
    baseEbMin: 12.50,
    trendStatus: "down",
    trendPct: -8.0,
    notes: "Synchro staple"
  }
];

if (typeof module !== 'undefined') {
  module.exports = { DEFAULT_CARDS, DEFAULT_WANTS };
}
